### ISSUE TITLE
Auto remove "\n" from token?

### ISSUE THREAD

**Issue by haozhu233** [OuhscBbmc/REDCapR#103]
My institution just upgraded REDCap to v 6.12.1 last week and we soon hit an interesting glitch. As it is caused by the new API method, which was introduced in v 6.11.0, I'm sharing it here as it may help others. 

For security concerns, I usually put my token in a token file (so I can git ignore it) and use read.file to import it into R. In some systems (in our case, a centOS shiny server was affected), R likes to put a carriage return "\n" at the end of that string. Unlike the old REDCap API, which will take that string and ignore that "\n", the new API method that Vanderbilt introduced in v 6.11.0 seems to be more strict and will treat "\n" as part of the token string. This bug is really hidden in the bushes as you cannot see it on a Mac or a Windows machine.

My current local solution is to put a sub "\n" around it. At the same time, I guess it doesn't hurt to add this little feature to this package as it's unlikely to really have a "\n" in a REDCap token.

**Comment by wibeasley** [comment]
Thanks @haozhu233 for noticing it and sticking through the solution.

I agree it doesn't belong in a strict API library, but I support the idea of improving the utility/helper features around it.  Similar to [`retrieve_token()`](https://github.com/OuhscBbmc/REDCapR/blob/master/R/retrieve-token.R) function.

**Comment by wibeasley** [comment]
@haozhu233, I was reviewing the past week's forum posts as saw [one about SAS having trouble with the trailing line break in the token](https://community.projectredcap.org/questions/5778/cant-use-api-with-sas-but-can-use-with-other-expor.html).  If you don't have access to the post, the short story is that a library like REDCapR, redcapAPI, or PyCap is preferable to a bunch of loose code that people share.  I love how the problem you identified and patched seamlessly propagated to everyone's code.  With loose code, multiple files at multiple institutions have to manually updated.

By the way, if you're storing credentials in a local (gitignored) file, see `retrieve_credential_local()` in https://github.com/OuhscBbmc/REDCapR/blob/master/R/retrieve-credential.R.  It mimics how things are stored in our LDAP-connected "token server".  Credentials are stored in a CSV like
https://github.com/OuhscBbmc/REDCapR/blob/master/inst/misc/example.credentials

It won't be radically different than what you're doing, but should reduce the code you have to write by a few lines.

**Comment by haozhu233** [comment]
@wibeasley, thanks for your kind words! I really like the concept of "loose code". It helps us to write more "durable" functions and allows users to think less when they are programming. Thank you for letting me know the term so now I can have a word to describe this feeling! ;)

Also, `retrieve_credential_local()` looks great! I'm gonna adopt it in the REDCap projects I'm working on. Thanks for letting me know!!
