### ISSUE TITLE
creating new column after combining baseline and stepdown descriptive stats

### ISSUE THREAD

**Issue by rpoudel** [OuhscBbmc/REDCapR#110]
Dr. Beasley,
I thought beside individual table of baseline and stepdown, it would be better to present in combined table of both events. Please check the following code whether I have done it correctly. 
@wibeasley 
baseline_alcohol_pc1 and stepdown_alcohol_pc1 are dataframes of descriptive stats of event: baseline and stepdown.

combined_base_step_pc1 <- dplyr::bind_rows(baseline_alcohol_pc1,stepdown_alcohol_pc1)
#values for new column
time_table <- data.frame(event = as.character(c("Baseline" , "Stepdown"))) %>% 
  dplyr::mutate(
    "`Period of Service`" =event) #name of new column
  dplyr::bind_cols(time_table,combined_base_step_pc1) %>%
  dplyr::select(-event) %>%
  
  knitr::kable(
    caption  = "Descriptive Statstics of CAGE Score of Primary Caregivers 1 for Alcohol in Stepdown and Baseline",
    align    = c("r"),
    format   = "markdown"
  )

**Comment by wibeasley** [comment]
@rpoudel, I assume you meant for this to go in the Waiver repo.  Will you please move it there?  Also, could you please

1. use syntax highlighting in the issue, so I can see the indentions better, (and maybe add indentions if they're not there), and  
1. link to your file, so I see the context of this operation?
