### ISSUE TITLE
Test retrieve_credential_mssql for bad input

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#115]
To avoid SQL injection, since RODBC doesn't support parameterized queries.

**Comment by nutterb** [comment]
I'm seeing all these hit my e-mail, but figured I'd suggest the `RODBCext` package, which _does_ support parameterized queries.

**Comment by wibeasley** [comment]
That's awesome, @nutterb.  Thanks.  I could have sworn I saw something like that, but I didn't find it for SQL Server, so I thought I had confused it with some DBI-compliant package that didn't support SQL Server.

Do you have much experience with `RODBCext`?  Any feel for how stable or well-supported it is?  I know ODBC isn't changing much, but I imagine those kinds of low-level calls are tricky to get right.

**Comment by nutterb** [comment]
I use `RODBCext` every day.  We are strictly forbidden from using SQL injection, and I've found `RODBCext` to be much easier to use anyway (I never have to worry about escaping or matching my single quotes to get a query to work).  

As far as stability, I think it's excellent.  If you look at the archive (https://cran.r-project.org/src/contrib/Archive/RODBCext/), there were three updates in the first month it hit CRAN; then one update in 2015, and one in 2016.  There is a github repository (https://github.com/zozlak/RODBCext) that lists all of four issues.  Plus, Professor Ripley is listed as one of the authors.  It's got a lot to speak in it's favor.

From personal experience, like I've said, it has been incredibly friendly to use _and_ has better security.  I've loved it so much, I'm not just a convert, but an active evangelizer.

**Comment by wibeasley** [comment]
I'm sold.  I appreciate your expertise & advise, @nutterb.
