### ISSUE TITLE
Exporting the report, not the project data

### ISSUE THREAD

**Issue by raheems** [OuhscBbmc/REDCapR#139]
Hi,
How to export the data in a "report". For example, in the REDCap sample R code, I was able to enter the content as "report" and put the report ID. How to do this in REDCapR package? 

Thanks

library(RCurl)
result <- postForm(
     uri='URL HERE',
     token='XXXX',
     content='report',
     format='csv',
     report_id='4390',
     rawOrLabel='raw',
     rawOrLabelHeaders='raw',
     exportCheckboxLabel='false',
     returnFormat='json'
)

**Comment by wibeasley** [comment]
Hi @raheems, REDCapR doesn't currently have a wrapper around that function.  I'm willing to add it in the future if people use it much.  It won't be in the next few weeks though.  Even though the code could be written in a few hours, I'll need another few hours to write a test suite for that function

I believe that @nutterb's [redcapAPI](https://github.com/nutterb/redcapAPI) package exports report.  Would that fit your needs?

**Comment by raheems** [comment]
Yes, redcapAPI fits my needs. Thank you for the update!
