### ISSUE TITLE
Export Survey Time-stamps

### ISSUE THREAD

**Issue by wtquirks** [OuhscBbmc/REDCapR#159]
Is it possible to export the time-stamps for the entered records? The redcap_read_oneshot function doesn't seem to do this. This would be helpful for my project because I would like to do a filter logic on dates.

**Comment by wibeasley** [comment]
I'm pretty sure that there's not an automatic timestamp available through the API.  If you can get one through the API playground, please let me know and reopen the issue.

However I bet it's relatively easy to (a) create your own field, (b) populate it with the '@NOW' action tag, and (c) hide or disable it from the user (with another action tag).  You *may* have to play with the settings so that it sets the timestamp for only the records that were modified in the GUI.

**Comment by firaswehbe** [comment]
@wibeasley I think you can get the timestamp for _surveys_ see `exportSurveyFields='true'` below from the api playground. I'm trying to get that as well using this package

```r
#!/usr/bin/env Rscript
library(RCurl)
result <- postForm(
    uri='https://redcap.nubic.northwestern.edu/redcap/api/',
    token='B000BE5427163CF44ADDC4EFB8859FCC',
    content='record',
    format='json',
    type='flat',
    rawOrLabel='raw',
    rawOrLabelHeaders='raw',
    exportCheckboxLabel='false',
    exportSurveyFields='true',
    exportDataAccessGroups='false',
    returnFormat='json'
)
print(result)
```

**Comment by firaswehbe** [comment]
Typical use case for us of the `surveyform_timestamp` survey variable is to plot survey cumulative response over time for our public surveys. When the curves flatten out we know to send reminders or post on other forums if we still need more responders. e.g. [here](https://github.com/DataCourse/backgroundwords/blob/d4e3a30cdb32c53e91d990de47bad27bc1795933/surveyanalysis.R#L12)

**Comment by rparrish** [comment]
Adding my vote for this as well. Will use @NOW in the meantime.

**Comment by dadrivr** [comment]
Adding my vote for this, as well.  Looking to do this with the `redcap_read()` function. (sorry I didn't see that this issue already existed!

**Comment by kevinmoran805** [comment]
I think this would make a great addition too. We use survey completion timestamps for automating things like payment and study randomization.

**Comment by wibeasley** [comment]
Thanks everyone on this thread for your input.  This is now available on the master.  Please tell me if it's not working the way you expected by starting a new issue.
