### ISSUE TITLE
Unknown SSL protocol error in connection to xxxx:443 

### ISSUE THREAD

**Issue by cristobalcar** [OuhscBbmc/REDCapR#160]
Hi all!
I've installed http://www.louisaslett.com/RStudio_AMI/ in AWS and also the REDCapR package.
I'm getting problem connecting to the server where REDCap is hosted with the SSL error :443
I'm stucked with this.... Any help??

**Comment by wibeasley** [comment]
Hi @cristobalcar, May I see the calling code?  Especially the REDCap URL?

**Comment by cristobalcar** [comment]
>  redcap_uri                  <- "https://redcap.alemana.cl/api/" 
>  token                       <- "xxxxxxxxx"
>  records_collapsed           <- NULL
>  fields_collapsed            <- NULL
>  
>      raw_text <- RCurl::postForm(
+              uri                        = redcap_uri
+              , token                    = token
+              , content                  = 'record'
+              , format                   = 'csv'
+              , type                     = 'flat'
+              , rawOrLabel               = 'raw'
+              , exportDataAccessGroups   = 'true'
+              , records                  = records_collapsed
+              , fields                   = fields_collapsed
+              , .opts                    = RCurl::curlOptions(ssl.verifypeer=FALSE)
+          )
Error in function (type, msg, asError = TRUE)  : 
  Unknown SSL protocol error in connection to redcap.alemana.cl:443 
------------------------------
> uri       <- "https://redcap.alemana.cl/api/"
> token            <- "xxxxxxxxxx"
> redcap_read(redcap_uri=uri, token=token)$data
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL connect error

**Comment by wibeasley** [comment]
I don't see a problem with that, but obviously I can't test it.  Can you confirm four things?
1. R is running the latest version (since those ssl certs are now packaged in R, and not RCurl, curl, or REDCapR).
1. REDCap is running the latest GitHub version (ie, `devtools::install_github(repo="OuhscBbmc/REDCapR")`)
1. The same error runs in RCurl, even when you completely leave off the 'records' and 'fields' parameters
1. The REDCap API playground is returning sensible values.

**Comment by cristobalcar** [comment]
The AMI is this:
RStudio	1.0.143	  	All 10GB SSD EBS store
R	3.4.0	  	RStudio on port 80 (HTTP)
 	 	  	Shiny at /shiny/rstudio
Julia	0.5.2	  	Jupyter at /julia
Ubuntu	16.04 LTS

**Comment by wibeasley** [comment]
Cool, I'll wait for the responses for 2-4 later.  In the meantime, does your code work from other machines, especially ones in the same university/hospital network?

**Comment by cristobalcar** [comment]
2 all updated
3 yes
4 it's OK

Finally I've tested in Postman and everything is OK....
I think its related to the AMI of AWS

**Comment by wibeasley** [comment]
That's outside REDCapR and way outside my expertise, but tell me if you see something that we can help with in the future.  Maybe start a new issue with whatever info has come to light by then.

It sounds like you're on the right track with Postman and those approaches.  But this document might give you additional ideas: 
https://cdn.rawgit.com/OuhscBbmc/REDCapR/master/inst/doc/TroubleshootingApiCalls.html
