### ISSUE TITLE
Access DAG list?

### ISSUE THREAD

**Issue by vortexing** [OuhscBbmc/REDCapR#163]
I cannot seem to figure out if/how I could access the list of data access groups in a project.  Basically it'd be great to be able to use redcap_metadata_read and get data access groups as well, but I realize DAG's are not part of the data dictionary.

The token is for a user who has access to all DAG's, FYI.  

Is there a way to report which DAGs are visible to a specific user regardless of whether there are any records in the project in that DAG (aka, if a DAG was empty, it would still be in the list).

Hopefully I'm just missing something. 

Thanks!

**Comment by wibeasley** [comment]
Hi @vortexing, the DAG is exposed in a column returned by the API's 'Export Users' method.  If you want to follow the pattern to create a function & pull request, I'll help you along.  If not, I should have time to add this & the tests in a few weeks.

> **Method Name**
> Export Users
>
>**Description**
>This method allows you to export the list of users for a project, including their user privileges and also email address, first name, and last name. Note: If the user has been assigned to a user role, it will return the user with the role's defined privileges.

**Comment by wibeasley** [comment]
@vortexing, This is on the dev branch now, and will be pulled in to the master within a few days.
