### ISSUE TITLE
Exporting records from REDCap to R

### ISSUE THREAD

**Issue by osoroe** [OuhscBbmc/REDCapR#166]
Hi,  i get this error when trying to export from REDCap. Cannot seem to figure out the problem. Could you give some help?

Error in exportEvents.redcapApiConnection(rcon) :  501: <?xml version="1.0" encoding="UTF-8" ?><hash><error>The requested method is not implemented.</error></hash>

**Comment by rparrish** [comment]
Please provide a [reproducible example](https://gist.github.com/hadley/270442).

**Comment by wibeasley** [comment]
I'm sorry, @osoroe , I thought I had responded to this.  any chance your inadvertantly blending code between REDCapR (ie, this package) and [redcapAPI](https://github.com/nutterb/redcapAPI) (ie, another R package for the REDCap API, developed by my friend @nutterb)?

https://github.com/nutterb/redcapAPI/blob/91e96c07ae5c77243a83fe16177e281093706c47/R/exportEvents.R

**Comment by nutterb** [comment]
@osoroe your error is definitely being returned by the [redcapAPI](https://github.com/nutterb/redcapAPI) package. The two easiest things to rule out are 

1. Are you using REDCap version 5.8.2 or higher?  (I hope so, that's a fairly old version of REDCap)
2. Did you copy your API URL correctly?  It is noted [elsewhere](http://sburns.org/2013/07/22/intro-to-redcap-api.html)

>At least at Vanderbilt, don't forgot the trailing slash at the end of the API URL string. Your site may differ but if you mess up the URL, nothing will work and you'll probably get 501 "Method Not Implemented" responses.

If these do not rectify the problem, please file an issue [over here](https://github.com/nutterb/redcapAPI/issues) and provide as much detail as you can about the code and the error it generates.

**Comment by osoroe** [comment]
Hi Will,
i have both packages but was using the REDCApR. I have attached the R file
i used.

Regards,
Eric

**Comment by wibeasley** [comment]
@osoroe, any chance you're at REDCapCon now?  I'm about to go to the 'External Modules' session, and could meet you afterwards.  The code you attached didn't come through.  Could you try to follow @rparrish's advice and paste a minimally reproducible example in the issue itself (and not a stand alone file).  Usually these things are only ~5 lines.

Your explanation doesn't seem to fit @nutterb's and my understanding of our packages and their functions.  I'm pretty that function is not in REDCapR.  @nutterb seems pretty sure it's in redcapAPI.  I have a feeling that you might be blending code from the two packages.

**Comment by osoroe** [comment]
Hi Willy,
Am not at the conference. Let me try to run the codes again and see what
happens.

Eric

**Comment by wibeasley** [comment]
Hi @osoroe, I assume this was resolved.  If not feel free to open a new issue that isolates the REDCapR code.
