### ISSUE TITLE
Tests break with dev version of devtools

### ISSUE THREAD

**Issue by krlmlr** [OuhscBbmc/REDCapR#169]
because `inst()` is not exported anymore.

**Comment by wibeasley** [comment]
Thanks, @krlmlr.  I hadn't noticed that it had been pulled into the new package [pkgload](https://github.com/r-lib/pkgload).

Note to self: 
https://github.com/hadley/devtools/blob/5517fdb9f4b655eaeffdc7e371db42cddcc679e4/NEWS.md#devtools-1131

> Code related to simulating package loading has been pulled out into a separate package, pkgload. The following functions have been moved to pkgload without a shim: clean_dll(), compile_dll(), dev_example(), dev_help(), dev_meta(), find_topic(), imports_env(), inst(), load_code(), load_dll(), ns_env(), parse_ns_file(), pkg_env(). These functions are primarily for internal use.
