### ISSUE TITLE
super-wide test projecct

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#178]
@thomasnwilson, related to the problems we had the other week, can you create a super wide (and short) test project on the bbmc instance?

Besides `record_id`, could you add 3000 column names that follow the pattern `tediously_long_variable_name_0001` ... `tediously_long_variable_name_3000`.  Include a single populated row, where the 3000 cells are populated sequentially 1 through 3,000.  That way, we have more assurance that the cells aren't being shifted.

I hope we don't have to start batching both horizontally and vertically.  That's probably enough motivation to develop the EAV routine more (See #145)

**Comment by thomasnwilson** [comment]
@wibeasley 

Sure thing.  Not sure if I can get to it today, but I will try.

**Comment by thomasnwilson** [comment]
It's going to take me a long time to create all of those variables.

**Comment by thomasnwilson** [comment]
...and even longer to enter the data.

@wibeasley

**Comment by wibeasley** [comment]
Would it help to autopopulate it in Excel (with sequencing) or R (and output the variable names to a csv)?

**Comment by thomasnwilson** [comment]
I don't trust those newfangled capabilities.  The only way to do something right is through a little sweat equity.

**Comment by thomasnwilson** [comment]
Closing this issue and expressing my sincerest apologies for not using my sarcasm font on my previous comments.  Shame on me.
