### ISSUE TITLE
read reports

### ISSUE THREAD

**Issue by hatemhosny** [OuhscBbmc/REDCapR#182]
how can I export reports created by the REDCap report builder?

great package, by the way 👍 
thanks

**Comment by wibeasley** [comment]
thanks, @hatemhosny.  Have you considered using [`redcapAPI::exportReports()`](https://www.rdocumentation.org/packages/redcapAPI/versions/1.3/topics/exportReports).  It's developed by my friend, @nutterb.  

Once I establish a better testing framework (that hits multiple versions of REDCap), @nutterb and I intend to [merge our two packages](https://github.com/OuhscBbmc/REDCapR/issues/133).

**Comment by nutterb** [comment]
Please note that if you `redcapAPI` is out of date on CRAN.  There were changes to the `Hmisc` package that require some updates that I haven't gotten published yet.  If you wish to use `redcapAPI`, I would recommend using 

`devtools::install_github("nutterb/redcapAPI", ref = "Version2")`

**Comment by hatemhosny** [comment]
thanks @wibeasley and @nutterb 

I re-installed redcapAPI from github as suggested

using that code:
``` R
library(redcapAPI)
rcon <- redcapConnection(uri, token)
mydata <- exportReports(rcon, reportid)
```

I get this error:

```
Error in if (meta_data$field_type[meta_data$field_name %in% x] == "checkbox") { : 
  argument is of length zero
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```
and lots of 
```
Warning messages:
1: In rbind(c("1", " field1"), c(" 2", " field2"), c(" 3",  ... :
  number of columns of result is not a multiple of vector length (arg 1)
2: In rbind(c("1", " field1"), c(" 2", " field2"), c(" 3",  ... :
  number of columns of result is not a multiple of vector length (arg 1)
```

I am running windows 10, R 3.4.2 and REDCap 7.3.1

**Comment by wibeasley** [comment]
@hatemhosny, reopen this dormant issue if you'd like.
