### ISSUE TITLE
possibly add fx that converts SPSS output to data dictionary format

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#222]
The function was essentially written already.  It would need tests though.

https://stackoverflow.com/a/51013678/1082435

I'm not sure if it would be used by many people --enough to keep it in the package and whatever small maintenance it requires.

**Comment by nutterb** [comment]
Truthfully, this feels more like a gist, or an unexported function (the function exists, but no promises). 

I'm sure there are edge cases in the SPSS output that won't get covered.  A gist is a lot easier to point people to without feeling obligated to make it work for them.  They can always use the gist as a starting point.

**Comment by wibeasley** [comment]
@nutterb, that's a good point, especially for the SPSS crowd.

I've released only one Gist.  I don't like the looseness of a Gist (compared to a package), but it turned out to be a lot easier for people to deploy than keeping [RedcapExamplesAndPatterns](https://github.com/OuhscBbmc/RedcapExamplesAndPatterns) updated.

If it lived in Gist, would there still be testthat tests for it?  If so, would testthat code live in the repo?  Maybe something this trivial (and manual) doesn't really need tests).

**Comment by nutterb** [comment]
If you want the convenience of the unit tests, I'd say an unexported function would be the way to go.  Or maybe a vignette.  It's an interesting case-study of preparing data for upload to REDCap.  Especially now that it is possible to upload data dictionaries through the API.

**Comment by wibeasley** [comment]
eh, I'm referencing the SO post in [Advanced REDCapR Operations vignette](https://ouhscbbmc.github.io/REDCapR/articles/advanced-redcapr-operations.html) and closing the issue.  

@nutterb, thanks for talking me out of maintaining a function for it.
