### ISSUE TITLE
redcap_read_oneshot errors with July 10  update?

### ISSUE THREAD

**Issue by voitmichaela** [OuhscBbmc/REDCapR#231]
I installed the new development version of the REDCapR package and whenever I attempt to use redcap_read_oneshot() to download data I get this error: 

> Error in inherits(ds, "data.frame") : object 'ds' not found
> In addition: Warning message:
> In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

I'm not the most API-savvy person, so I'm not sure what this means or applies to. Seems it has to do with the update on July 10th.

**Comment by wibeasley** [comment]
@voitmichaela, I see your later closed this issue?  If you found a solution, will you please describe it so it might help others?  

I'm curious too, so I can make updates an easier transition for others in the future.
