### ISSUE TITLE
redcap_read() leaves out identifiers with leading zeros

### ISSUE THREAD

**Issue by TrevorKMDay** [OuhscBbmc/REDCapR#241]
We recently added subjects with leading zeroes to our project (we renamed the REDCap identifier field, so ours is in the first column `data.idnum`), and it seems `redcap_read` won't pass them through, even though they are identified by the function (e.g. it gives the progress message `Reading batch 1 of 1, with subjects 1017 through 180732 ...`, where we have actually stored "1017" and "001017"). 

Renaming them to e.g. "101017" works fine, and attempting to force it with `records = "1017"` or `"001017"` doesn't work.

Is this intended behavior? I don't know of any issues REDCap itself has with leading zeroes. 

it would also be nice to preserve our identifiers as written, instead of having `redcap_read` silently strip them.

**Comment by wibeasley** [comment]
@TrevorKMDay, Is it *stripping* the leading zeros from the string?  Or is it converting the string to a number?

if the latter, set `guess_type` to false.

**Comment by TrevorKMDay** [comment]
It seems the resulting data frame has `idnum` as an integer, but the leading-zero/four digit identifiers are still not present. It would also be nice if the record identifier field was always treated as a character string, I don't know if that's possible. 

Is `guess_type` usable in 0.9.8 or would I have to install from git in order to use it?

**Comment by wibeasley** [comment]
@TrevorKMDay, an integer will never have a leading zero in R (and most languages).  It needs to be a string (like how most people store phone numbers, etc).

Yes, install from GitHub:
```r
devtools::install_github(repo="OuhscBbmc/REDCapR")
```

**Comment by TrevorKMDay** [comment]
Yeah, I understand.  

I meant to suggest the record ID field should always be treated as a string by `redcap_read`, like a zip code would be. Using `guess_type` has the side effect that all the numeric variables that should be converted now aren't. 

Thanks for your help.

**Comment by wibeasley** [comment]
>has the side effect that all the numeric variables that *should* be converted 

If you have ideas for operationalizing "should", we're all ears.

As people have discussed before, even looking at the validation in the project's metadata won't fully help, becuase the validation can be bypassed (or added later) --so the variable could sitll potentially contains strings.
