### ISSUE TITLE
Logging (audit trail) 

### ISSUE THREAD

**Issue by wrlemast** [OuhscBbmc/REDCapR#243]
I am trying to find a way to pull the logging data as a way of tracking employee productivity.

**Comment by wibeasley** [comment]
@wrlemast, I'm not seeing any API method to retrieve the logging info.  If that doesn't exist, there's nothing for REDCapR to call.

Two options I see:
1. pull from MySQL directly
1. request the feature be added on the [community site](https://community.projectredcap.org/).

Both are feasible.  I'm willing to discuss it more if you'd like.

**Comment by wrlemast** [comment]
@wibeasley, Also I do not have access to the community site.

**Comment by wibeasley** [comment]
It's not my favorite that the community site isn't open to API developers.  You'll need to talk to your REDCap admins for both requesting the feature on the site, and to access the underlying database.  

Politically, they'll be understandably reluctant to open up the database to you.  Maybe they'll be willing to regularly export a subset of data that pertains just to your project_id.

Technically, look around line 244 for the sql reading from the user table.  You'd do something similar with the 'odbc' package (but pull from the table containing the audit info you want)
https://github.com/OuhscBbmc/REDCapR/blob/master/vignettes/SecurityDatabase.Rmd

**Comment by wibeasley** [comment]
@wrlemast, I hope this effort accessing the database directly went well.  Here is a recent thread that might be relevant (that your site REDCap admin can access and share):

https://community.projectredcap.org/questions/66080/logging-database-table-1.html
