### ISSUE TITLE
The "export_survey_options" is not recognized as valid argument

### ISSUE THREAD

**Issue by firaswehbe** [OuhscBbmc/REDCapR#247]
This is related to #159. I'm using version 0.9.8 downloaded from CRAN.

It's not recognizing the `export_survey_options` argument. Tried both in `redcap_read` and `redcap_read_oneshot` functions.

**Comment by wibeasley** [comment]
Hi @firaswehbe, can you see if you get this with the version on GitHub?  I'm working on some features & fixes before releasing a new version to CRAN.

https://github.com/OuhscBbmc/REDCapR#installation-and-documentation

```r
install.packages("remotes") # Run this line if the 'remotes' package isn't installed already.
remotes::install_github(repo="OuhscBbmc/REDCapR")
```

**Comment by wibeasley** [comment]
@firaswehbe, was this resolved?  If not, feel free to reopen the issue and explain the problem encountered with the newest version on GitHub.
