### ISSUE TITLE
`checkmate` should be in Imports or Depends, not Suggests

### ISSUE THREAD

**Issue by dtenenba** [OuhscBbmc/REDCapR#255]
Hi,

I'm working with a package that has REDCapR in its Imports field.
If I install this package with `install.packages()`, it does not install checkmate.
And yet, normal use of REDCapR (calling `REDCapR::redcap_variables()`) contains calls (via `::` to functions in checkmate), which fail with errors since checkmate is not installed.

Though the [R-exts manual](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-Dependencies) is a bit ambiguous in places (like where it says "Namespaces accessed by the ‘::’ and ‘:::’ operators must be listed here, or in ‘Suggests’ or ‘Enhances’", it is also clear that "[t]he ‘Suggests’ field uses the same syntax as ‘Depends’ and lists packages that are not necessarily needed." 

In the case I describe, the checkmate package is clearly needed so I believe this is a bug and that checkmate should be moved from Suggests to Imports. 

@vortexing

**Comment by wibeasley** [comment]
@dtenenba, I absolutely agree.  I'm guessing I suggested checkmate when it was in only minor functions.  And now you're right that it's in critical REDCapR functions.

Thanks for diagnosing the problem and explaining things so clearly.  The code passes the tests on my local machine.  Assuming Travis & AppVeyor are cool, I'll pull them into the master branch within GitHub within the hour.  (*i.e.*, run `remotes::install_github(repo="OuhscBbmc/REDCapR")`).

@dtenenba (or anyone else), do you have an opinion whether I should resubmit to CRAN just for this?  I still remember getting Ripleyed when I resubmitted to CRAN twice within a three-month period.

**Comment by dtenenba** [comment]
@wibeasley I can't speak for CRAN but when I worked for Bioconductor we would not let packages in that had this problem. 

If you can handle the Ripleying then I say resubmit.

**Comment by dtenenba** [comment]
And thanks for the quick fix!
