### ISSUE TITLE
filter_logic does not work with survey fields such as "timestamp", "complete" 

### ISSUE THREAD

**Issue by beib** [OuhscBbmc/REDCapR#262]
I would like to filter based on fields that were not created by users, but automatically generated by REDCap, such as timestamp and complete status. However, `filter_logic` seems to only work with fields that are created by users but not for example, timestamp. 

The problem I have encountered, is that when responses are partial missing, sometimes (but not all the time), timestamp information is listed as "[not completed]". Because of this, redcap_read() would not parse date and time and throws an error. I would like to filter out rows with timestamp as [not completed].

Here is an example of data that didn't work.

record_id | redcap_repeat_instance | sleep_diary_timestamp
-- | -- | --
1435 | 1 | [not completed]
1436 | 1 | 5/11/19 12:13
1436 | 2 | 5/11/19 12:13
1436 | 3 | [not completed]
1437 | 1 | 5/11/19 12:14
1437 | 2 | [not completed]
1438 | 1 | 5/11/19 12:15
1438 | 2 | 5/11/19 12:15
1438 | 3 | [not completed]
1439 | 1 | 5/11/19 12:16
1439 | 2 | [not completed]
1440 | 1 | [not completed]
1440 | 2 | [not completed]

**Comment by wibeasley** [comment]
@beib,  is the `sleep_diary_timestamp` variable being interpreted as a string or as a date?  If it's a string, and if you can format it in [ISO 8601](https://www.explainxkcd.com/wiki/index.php/1179:_ISO_8601), you should be able to filter.  Something like
```
'2019-05-01' <= [sleep_diary_timestamp] && [sleep_diary_timestamp] <= '2019-05-31'
```

**Comment by beib** [comment]
I was previously using 0.10.0, and it throws this error `Error: Column `sleep_diary_timestamp` can't be converted from POSIXct, POSIXt to character`. I guess it failed to convert. This problem is now gone now that I just updated to the latest github version 0.10.2. Now this whole field is read in as character, and I can do post hoc processing. Thank you for replying so quickly! :)

**Comment by wibeasley** [comment]
Glad to hear it.  Yea, the ramifications of issue #257 had a lot of bang for the buck.
