### ISSUE TITLE
REDCapR: redcap_read function gives error in R version 3.6.1 and not 3.5.3 

### ISSUE THREAD

**Issue by sybandrew** [OuhscBbmc/REDCapR#272]
Hello, 
There is an issue with the **redcap_read** function in the package **REDCapR** for people using the new version of R (3.6.1) compared to the older R version (3.5.3). 

### What I did: I attached two images: **REDCapR photo 1** and **REDCapR photo 2** of the code I ran in R markdown and the error that I got at the end of the code.

<img width="492" alt="REDCapR photo 1" src="https://user-images.githubusercontent.com/57678103/68786144-475f7080-060d-11ea-9e47-675eee0b4c83.png">

<img width="534" alt="REDCapR photo 2" src="https://user-images.githubusercontent.com/57678103/68784272-4c6ef080-060a-11ea-9617-93d9de6353e5.png">

### What I was expecting: I was expecting the last part of that code in image: **REDCapR photo 1 & 2** to import my data from REDCap but it didn't. I looked up the error and troubleshooted several times but nothing worked. Then 2 of my colleagues tried. 

1. The first colleague had a Mac and tried running the same code on the new version of R 3.6.1 and got the same error
2. The second colleague tried on her lenovo laptop with R version 3.5.3 and was able to run the code with no problem

### What actually happened: I got an error using R version 3.6.1 on lenovo laptop which can be seen in **REDCapR photo 2**. 

<img width="534" alt="REDCapR photo 2" src="https://user-images.githubusercontent.com/57678103/68784354-690b2880-060a-11ea-8e9e-4fd74d85fc05.png">

I ended up using the function **redcap_read_oneshot** instead of **redcap_read** which worked and is shown in image **REDCapR photo 3**.  However, I read that **redcap_read** is used for larger datasets and if larger datasets need to be imported, I would like to use this function. Please help. Thank you.

<img width="593" alt="REDCapR photo 3" src="https://user-images.githubusercontent.com/57678103/68784632-dcad3580-060a-11ea-8a7e-226f3ebb1543.png">

Best regards, 
Sybandrew

**Comment by wibeasley** [comment]
@sybandrew, thanks for providing so much detail.  There's a chance that it's not a difference in R, but a difference in the packages.  Will you please update all the packages (`update.packages()`) and install the newest version of REDCapR on GitHub (`remotes::install_github(repo="OuhscBbmc/REDCapR")`)?  You should restart RStudio first.

If the problem still remains, can you please tell me your version of REDCap, and the results of `traceback()`?

**Comment by sybandrew** [comment]
Hello, 
I followed your instructions. See photo **REDCapR photo 5**

<img width="622" alt="REDCapR photo 5" src="https://user-images.githubusercontent.com/57678103/68791453-58ad7a80-0617-11ea-9362-f4468a09d1a3.png">

I still got the error. Please see image **REDCapR photo 4**. 

<img width="605" alt="REDCapR photo 4" src="https://user-images.githubusercontent.com/57678103/68791178-c9a06280-0616-11ea-95bd-5529f82486cd.png">

The version of REDCapR is **‘REDCapR’ version 0.10.2.9002**

Thank you

**Comment by wibeasley** [comment]
Cool.  A few more questions
1. What version of REDCap?
1. Are all the packages updated (with `update.packages()`)?
1. Did this ever work?  If so, when did it stop working?
1. What institution are you?
1. What are the results of `REDCapR::redcap_metadata_read()`?
1. If the metadata fails, can you send me your data dictionary? (email wibeasley@hotmail.com)

This might be related to an issue from yesterday (#269)

**Comment by sybandrew** [comment]
1. What version of REDCap?
The version of REDCap being used is 9.3.3 which was recently updated last month

2. Are all the packages updated (with update.packages())?
Yes, all the packages were updated using update.packages(). However, I always check for updates so none appeared. See first image. However, I did it again and ran a traceback, please see second image 

<img width="622" alt="REDCapR photo 5" src="https://user-images.githubusercontent.com/57678103/68795303-b42f3680-061e-11ea-9255-97ff4ec30ec4.png">

<img width="639" alt="REDCapR photo 7" src="https://user-images.githubusercontent.com/57678103/68795597-4cc5b680-061f-11ea-8161-0d672d492b3a.png">

3. Did this ever work? If so, when did it stop working?
Yes, this function did work at one point for users but I am not sure when it stopped working. 

4. What institution are you?
I am a REDCap administrator at CHOP (Children's Hospital Of Philadelphia) 

5. What are the results of REDCapR::redcap_metadata_read()?
I still get an error with this as well. See image below

<img width="602" alt="REDCapR photo 6" src="https://user-images.githubusercontent.com/57678103/68795193-76321280-061e-11ea-9cb7-a5d41ab93e0e.png">

6. If the metadata fails, can you send me your data dictionary? (email wibeasley@hotmail.com)
I am waiting for permission from a client to send you their data dictionary. Once, I get an answer I will email you.

Thank you.

**Comment by wibeasley** [comment]
This wasn't the original source of the problem, but could you 
1. remove the arguments from `redcap_metadata_read()`, besides the uri and token?  The `events` isn't a parameter of the [metadata](https://ouhscbbmc.github.io/REDCapR/reference/redcap_metadata_read.html).  
1. if that works, add the `fields` parameter back, and see what happens.

**Comment by sybandrew** [comment]
Good morning, 
I did that and got the same error, see image below. I had previously did this during my trouble shooting with functions **redcap_metadata_read** and **redcap_read** to see if the field or eventnames may have been the issue. 

<img width="596" alt="REDCapR photo 8" src="https://user-images.githubusercontent.com/57678103/68862913-4fc2b480-06bc-11ea-84db-64576bc008ce.png">

**Comment by sybandrew** [comment]
I also ran a traceback(), see image below. 

<img width="615" alt="REDCapR photo 9" src="https://user-images.githubusercontent.com/57678103/68863825-112df980-06be-11ea-9b3a-419d8a757d08.png">

**Comment by sybandrew** [comment]
I sent you an email with the error I found along with some questions. Thanks

**Comment by wibeasley** [comment]
@sybandrew and I worked on this and determined that the problematic character in the data dictionary was a *curly* single quote (as opposed to a *straight* curly quote).  This is very similar to the issue (and solution) raised by @vortexing in #269 two days before this one.

The [solution](https://github.com/OuhscBbmc/REDCapR/commit/7367180641158d6ef6cae39ac4886efb43248e36) to #269 also fixed this guy.  As a precaution, we included a [different type of curly/slanty single quote in the test suite](https://github.com/OuhscBbmc/REDCapR/blob/master/inst/test-data/problematic-dictionary/problematic-dictionary.csv), so a regression bug is less likely.

If someone in the future comes across a character that causes problem, please follow my request in 
https://github.com/OuhscBbmc/REDCapR/issues/269#issuecomment-553089023:

> If anyone encounters something similar, please consider 
> 1. creating a new issue that references this one (ie, include the text "Issue #269")
> 2. in the issue, attach the your data dictionary, I'll isolate the problematic fields and include them in the live version of  [problematic-dictionary.csv](https://github.com/OuhscBbmc/REDCapR/blob/7367180641158d6ef6cae39ac4886efb43248e36/inst/test-data/problematic-dictionary/problematic-dictionary.csv).  If you're uncomfortable sharing your dictionary with the world, either (a)  isolate the fields yourself before attaching it, or (b) email it to me.
> 
> If we can't find a way for REDCapR to gracefully adapt, we'll at least try to provide a better error message.

Here are some screenshots of how the curly quote looks in REDCap and in the dictionary (viewed as vanilla csv)

![image](https://user-images.githubusercontent.com/1372890/70013180-76963d00-153c-11ea-8064-ac300ca79336.png)

![image](https://user-images.githubusercontent.com/1372890/70013272-aba28f80-153c-11ea-8f8e-ec99801271e2.png)


Here is a description that distinguishes the types of quotes.  

https://practicaltypography.com/straight-and-curly-quotes.html
![image](https://user-images.githubusercontent.com/1372890/70013381-0936dc00-153d-11ea-9dfd-2a7fc4f6b261.png)

Note that what is good with humans is trickier for computers.
![image](https://user-images.githubusercontent.com/1372890/70013471-62067480-153d-11ea-874f-45802d7eea44.png)
