### ISSUE TITLE
Error in inherits(ds, "data.frame") : object 'ds' not found

### ISSUE THREAD

**Issue by begavett** [OuhscBbmc/REDCapR#290]
`> REDCapR::redcap_metadata_read(redcap_uri = myURI, token = myToken)`
Error in inherits(ds, "data.frame") : object 'ds' not found

**Comment by wibeasley** [comment]
Hi @begavett, thanks for taking the time to report this.  Can you provide any additional information?
 And have you seen the [TroubleshootingApiCalls vignette](https://ouhscbbmc.github.io/REDCapR/articles/TroubleshootingApiCalls.html#exporting-from-redcap-to-r-using-redcapr)?  Specifically, this part?

> Can the user export their data dictionary? Sometimes the problem exists within the metadata/dictionary, instead of the actual data values. Verify the structure and content of this specific project is interpretable by your local environment.
>
>
>```r
> library(REDCapR) #Load the package into the current R session, if you haven't already.
> redcap_uri       <- "https://the.urlofyourinsitution.edu/api/"
> token            <- "your-secret-token"
> redcap_metadata_read(redcap_uri=uri, token=token)
>```
> If this fails, see “Problems in the project’s metadata/dictionary.” under Gotchas below.

**Comment by begavett** [comment]
Hi @wibeasley 

I noticed the exact same error appears when using `redcap_read`, but not when using `redcap_read_oneshot`. When using `redcap_read_oneshot`, I am able to correctly read in the data from REDCap.

**Comment by wibeasley** [comment]
Ok, this makes sense, and is consistent with #272.  But please provide more information so someone can help you better.

What happened when you followed the “Problems in the project’s metadata/dictionary.” in the troubleshooting vignette?  Several people gave input when we wrote it, for the situation that I think you're in.

**Comment by begavett** [comment]
Thanks for referring me to #272. Turns out the problem was that, in one of my fields, a double quotation mark may have been interfering with the proper parsing of the field. After removing that, the call to `redcap_metadata_read` worked.

**Comment by begavett** [comment]
Thank you for alerting me to #272. I didn't originally encounter that issue in my search. Using a text editor, I found some non-ASCII characters using a regex search for [^\x00-\x7F]+ and then replaced those with standard characters. That worked for me, so now I am able to successfully read in the data dictionary using `redcap_metadata_read`.

**Comment by wibeasley** [comment]
@begavett, I'd really like to build up a test be of problematic characters.  

1. Will you please send an excerpt of the dictionary that contains the problematic characters?  I'd really like to continue building the [bank of problematic values](https://github.com/OuhscBbmc/REDCapR/blob/master/inst/test-data/problematic-dictionary/problematic-dictionary.csv)  that should be handled correctly. 

1. I'm also curious about why the encoding measures in [`kernel_api()`](https://github.com/OuhscBbmc/REDCapR/blob/master/R/kernel-api.R) didn't address this.  Are you running the latest version from GitHub?  What version of REDCapR?

1. I like your regex search mentioned above.  I may include that in the Troubleshooting document.

**Comment by begavett** [comment]
The problematic characters for me were:
− ("minus sign")
“ ("left double quotation mark")
” ("right double quotation mark")

There were also &nbsp; characters picked up by my regex search, but I'm not sure if they were causing any problems (I made my changes in batch so I wasn't able to test individual characters for problems). 

This was done in REDCap 9.6.1 using v2.2 of redcapAPI and v0.10.2.9005 of REDCapR.

**Comment by wibeasley** [comment]
@begavett, will you please go to the "Project Revision History" tab and download the last problematic dictionary.  And then please send me the rows of the csv (at wibeasley@hotmail.com) that you think might have caused problems? 

As you can see from the [existing bank](https://github.com/OuhscBbmc/REDCapR/blob/master/inst/test-data/problematic-dictionary/problematic-dictionary.csv) I won't include your actual item.  Just the problematic characters in the midst of otherwise meaningless metadata.

![image](https://user-images.githubusercontent.com/1372890/72862527-1c3f7000-3c93-11ea-9c61-5bbf8234cb68.png)

**Comment by wibeasley** [comment]
@begavett, I've copied the characters you listed above and included them in the [problematic-dictionary.csv](https://github.com/OuhscBbmc/REDCapR/blob/master/inst/test-data/problematic-dictionary/problematic-dictionary.csv).  All the tests pass under the current version of REDCapR.  But there's a chance that using the GitHub comments as a middleman subtly sanitized the characters.

I'd still like to see the exact few lines of the data dictionary with those characters you mentioned above --especially if the current version of REDCapR is still throwing an error with them.  Building up the existing bank would help the package be more robust for everyone.  If you're willing, please reopen the issue and include the exact lines.  Or email the part of the data dictionary containing those variable descriptions.
