### ISSUE TITLE
checkmate not found with dependency discovery tools

### ISSUE THREAD

**Issue by pwildenhain** [OuhscBbmc/REDCapR#298]
Whenever I run [`renv::snapshot()`](https://rstudio.github.io/renv/reference/snapshot.html) or [`rsconnect::writeMainfest()`](https://rstudio.github.io/rsconnect/reference/writeManifest.html) in my projects that use `REDCapR` it fails to find the `checkmate` dependency 🤷‍♂ 

An easy workaround is to just insert `library(checkmate)` somewhere in my code, but I'm sure there is a better solution.

To be clear, installing the package works fine, it's just the dependency discovery that fails. If you think this is worth investigating, I'm happy to try and make a reproducible example. I also understand if you think this falls out of the scope of this package. But the fact that the problem persists across multiple tools makes me think the wires are crossed somewhere in `REDCapR`

**Comment by wibeasley** [comment]
Thanks @pwildenhain for the explanation.

Does this happen with the GitHub version of REDCapR?  I haven't pushed to CRAN in a few months.
https://github.com/OuhscBbmc/REDCapR/issues/255

**Comment by pwildenhain** [comment]
The GitHub version did the trick 👌 thank you!
