### ISSUE TITLE
redcap_download_file_oneshot download file from repeated instrument

### ISSUE THREAD

**Issue by zhangrz2019** [OuhscBbmc/REDCapR#299]
In the default file download function, I could not download file from any repeated instrument whose redcap_repeat_instance are greater than or equal to 2. Is there a way to specify redcap_repeat_instrument and recap_repeat_instance in the function redcap_download_file_oneshot?

Thanks,

**Comment by wibeasley** [comment]
1. what is the behavior or error message?
1. is the download successful in the API playground?

**Comment by zhangrz2019** [comment]
The problem was that when the file was saved in a repeated instrument, to ping point the file, I will need to specify redcap_event_name, redcap_repeat_instrument and recap_repeat_instance. By looking at the source code in redcap_download_file_oneshot( ), I realized the object post_body only specify one of the three variables - redcap_event_name. No where in the script adds repeat_instrument and repeat_instance in post_body. As such, only the file in the first instance of the repeated form will be downloaded. 

To resolve this, I manually specified ab object post_body and added variables repeat_instrument = <name of the repeat instrument> and repeat_instance = 2. Then I used REDCapR:::kernel_api(<redcap_uri>, post_body, NULL) and the output was successful and indicated the file that I intended to download.

I added the following in the script of redcap_download_file_oneshot( ):
...
if (0L < nchar(event)) 
        post_body$event <- event
    if (!is.null(repeat_instrument)) {
        if (is.null(repeat_instance)) {
            stop("You must specify repeat_instance when specified repeat_instrement");
        }
        post_body$repeat_instrument = repeat_instrument;
        post_body$repeat_instance = repeat_instance;
    }
...

The custom function verbose_prepare and kernel_api needs to specify package location. by adding REDCapR::: in front of them. 

I wonder if I will need to do the same for redcap_upload_file_oneshot( ).

**Comment by zhangrz2019** [comment]
In addition to the above comment, I also added repeat_instrument = NULL, repeat_instance = NULL, when initializing the parameters for the function redcap_download_file_oneshot( ).

**Comment by wibeasley** [comment]
@zhangrz2019, that sounds great.  When we added the function for downloading files, repeating instruments hadn't been developed yet.

It sounds like you're pretty far along.  Are you comfortable submitting a pull request?

**Comment by zhangrz2019** [comment]
While I am OK with pull request, I am not sure how to submit it.

**Comment by wibeasley** [comment]
#300 should good.  "Submit" probably was the best verb I could have chosen.  Thanks, I can look at it this weekend and add some tests.

**Comment by wibeasley** [comment]
@zhangrz2019, I just isolated your code (from https://github.com/OuhscBbmc/REDCapR/pull/300#issue-384532255) and included it in the commit linked immediately above.  Did I miss anything? Does it work in your application?

I'll need to add some tests before pulling it into the master branch.

**Comment by zhangrz2019** [comment]
Hello Will:

The script worked in my application.

Thanks,

p.s: How do I submit a pull request?
________________________________

**Comment by wibeasley** [comment]
@zhangrz2019, glad to hear it.

For a pull request, here's GitHub advice specific to PRs. 
 Notice there's essentially a whole book, if you navigate the left-hand panel. 
 https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

Speaking of books, you may be interested in Jenny Bryan & Jim Hester's [Happy Git and GitHub for the useR](https://happygitwithr.com/).
