### ISSUE TITLE
Error when passing httr options

### ISSUE THREAD

**Issue by BastienRance** [OuhscBbmc/REDCapR#307]
Hello,
Thank you very much for this package. It is such a great way to interact with REDCap!

REDCapR is returning an error when using Curl options.

Code:
```
redcap_read_oneshot(redcap_uri=uri,
                                token=token,
                                config_options = httr::config(ssl_verifypeer = 0L, ssl_verifyhost = 0L)
  )
```
Response:
```
Error in redcap_read_oneshot(redcap_uri = uri, token = token, config_options = httr::config(ssl_verifypeer = 0L,  : 
  Assertion on 'config_options' failed: Must have length 1, but has length 7.
```
This code used to work very well.

The error is launched by this line: `checkmate::assert_list(     config_options            , any.missing=TRUE , len=1, null.ok=TRUE)`
Is the length of the list supposed to be one ?

Thank you very much for your help.

REDCap version: 10.0.14
REDCapR version: 0.11.0
OS: linux

**Comment by wibeasley** [comment]
@BastienRance, yeah, your'e right.  I didn't realize the `len` parameter is a little different than for other checkmate functions.  I just removed that length constrains from the dev branch (not the master).  Can you see if that fixes this issue?  

If so, I'll push to the master in a few days.  There were some small tidyverse changes underneath that create havoc in the test suite.  The diagnostic messages are just different enough to fail the checks.

**Comment by BastienRance** [comment]
Works like a charm! Thank you very much.
