### ISSUE TITLE
redcap_write: would like to decide weather writting is 'overwrite' or 'normal'

### ISSUE THREAD

**Issue by Auricap** [OuhscBbmc/REDCapR#315]
Hi, 
This parameter is set by default to 'overwrite' but I would like that the parameter is set to normal in some cases in which I don't want empty values to overwrite exiting ones. It would be great if this parameter could be set up as input when calling redcap_write.
Thank you!
PS- Great package by the way!very easy to use and user friendly!

**Comment by wibeasley** [comment]
Hi @Auricap, good suggestion.  We haven't had the need for that yet, but happy to add it if it accommodates others.  Will you try the dev branch and tell me if it works as expected?  If not, please provide a reproducible example.

```r
remotes::install_github(repo="OuhscBbmc/REDCapR", ref="dev")
```

**Comment by wibeasley** [comment]
@dmongin, I just noticed that you recently had forked and did something similar --with a little different parameterization.  Do you want to see if the new feature meets your needs too?

https://github.com/dmongin/REDCapR/commit/ddd26e76aef48ceda461315a2f8915f823e279ea

![image](https://user-images.githubusercontent.com/1372890/99840020-5c7cb280-2b31-11eb-9841-fa9ac7ff44d2.png)

**Comment by Auricap** [comment]
> Hi @Auricap, good suggestion. We haven't had the need for that yet, but happy to add it if it accommodates others. Will you try the dev branch and tell me if it works as expected? If not, please provide a reproducible example.
> 
> ```r
> remotes::install_github(repo="OuhscBbmc/REDCapR", ref="dev")
> ```
Wow that was fast, thank you! I will take a look to the changes and let you know!

**Comment by Auricap** [comment]
Just tested, works wonders. Looking forward to the prod version. Thanks again!

**Comment by dmongin** [comment]
> 
> 
> @dmongin, I just noticed that you recently had forked and did something similar --with a little different parameterization. Do you want to see if the new feature meets your needs too?
> 
> [dmongin@ddd26e7](https://github.com/dmongin/REDCapR/commit/ddd26e76aef48ceda461315a2f8915f823e279ea)
> 
> [![image](https://user-images.githubusercontent.com/1372890/99844323-88e7fd00-2b38-11eb-895d-ca3cd62b1b95.png)](https://github.com/OuhscBbmc/REDCapR/network)

It is actually my needs, we are working on the same project with Auricap.
