### ISSUE TITLE
Compiling "Check All That Apply" Options into One Column When Exporting

### ISSUE THREAD

**Issue by Ashley-Jorgensen** [OuhscBbmc/REDCapR#324]
In the recent upgrade for REDCap, there is a feature within reports where you are able to "combine checkbox options into single column of only the checked-off options (will be formatted as a text field when exported to stats packages)". 

Typically when exporting data via the reports section or the API, the checkbox questions are treated as different columns in the csv or data that is exported (see image of fake data exported to csv below). 
![image](https://user-images.githubusercontent.com/52047033/109564701-0e1f6e00-7aa7-11eb-854e-626862d49a72.png)

When combining the checkbox options into a a single column from the reports section, you get the following in the exported data (see image below). 
![image](https://user-images.githubusercontent.com/52047033/109564828-33ac7780-7aa7-11eb-899d-679f8883bf6a.png)

Normally the first method would be fine, but recently we had to send our data dictionaries to NIMH in order for them to create data structures. The variable name and choices in our data dictionary (shown below) matched the data exported in the 2nd image but not the 1st and this caused some confusion. Is there a way to update REDCapR with similar functionality so that one is able to combine checkbox options when exporting the data to R? 
![image](https://user-images.githubusercontent.com/52047033/109564416-a79a5000-7aa6-11eb-8371-7adffe45db90.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - REDCap version: 10.5.1
 - REDCapR Version: 0.11.0

**Comment by wibeasley** [comment]
@Ashley-Jorgensen, it doesn't look like the API itself supports this option.  Below are 10.5.1 screenshots from the "export report" and "export records" playground.  But it's not possible with the newly-added `redcap_download_report()` (#326).  I've added the following example to the function's online documentation.  Reopen this issue if this doesn't address your need.

```r
# Return condensed checkboxes Report option:
#   "Combine checkbox options into single column of only the checked-off
#   options (will be formatted as a text field when exported to
#   stats packages)"
col_types_2 <- readr::cols(
  record_id          = readr::col_integer(),
  race               = readr::col_character()
)

REDCapR::redcap_report(
  redcap_uri = uri,
  token      = token,
  report_id  = report_2_id,
  col_types  = col_types_2
)$data
```
output:
```
5 records and 2 columns were read from REDCap in 0.4 seconds.  The http status code was 200.

  record_id race
1         1    5
2         2  3,5
3         3  4,5
4         4  2,5
5         5  1,6
```


### Playground screenshots

![image](https://user-images.githubusercontent.com/1372890/125225971-cbac4000-e295-11eb-908d-b9fcbde9aa61.png)

![image](https://user-images.githubusercontent.com/1372890/125226065-f7c7c100-e295-11eb-93e7-fd5910e1ec91.png)
