### ISSUE TITLE
New Vignette: REDCap to R to R Markdown

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#332]
Create a new vignette that will support the Aug 12, 2021 [R/Medicine Conference](https://r-medicine.org/) workshop organized by @higgi13425.

1. Introduce REDCap for novices
    * you probably have REDCap at your institution (w/ map & contact names)
    * test vs production projects
    * data entry validation strategies to prevent errors
    * when building an instrument/form, leverage existing standards and forms that have already been vetted by committees.
    * surveys vs conventional data entry forms
    * security & PHI
    * overview of how REDCap connects to other systems and other collaborators.  Tease Kenneth's upcoming segment.
1. EMR-ish data exists in a REDCap project.  A readonly API token is publically available
2. R calls [`REDCapR::retrieve_credential_local()`](https://ouhscbbmc.github.io/REDCapR/reference/retrieve_credential.html) to retrieve the token & URL
3. R calls [`REDCapR::redcap_read()`](https://ouhscbbmc.github.io/REDCapR/reference/redcap_read.html) and receives a data.frame.
4. An Rmd file bundles those previous two steps and produces an html document that contains
    1. A peak at the data.frame (with a warning that PHI would be exposed in a real example)
    2. Basic graphs
    3. An NIH-style table of demographics --probably using the [codified](https://ouhscbbmc.github.io/codified/) package.
1. Include links to training documentation & videos.  Encourage them to talk to their site's REDCap admin

(*Reminder to myself, there's a Google Docs we're using to organize thoughts for workshop. Look for an email from Peter Higgins.*)

edited with @higgi13425, Kenneth McLean, & Daniella Mark

**Comment by higgi13425** [comment]
In theory, 3 parts to workshop
1. How to Use Excel for Medical Research - Pitfalls of excel, best practices for preventing data errors, why you should use REDCap and R instead - Peter
2.  Introduction to REDCap, how to use, how to get data out - Will
3. Multicenter studies in REDCap with CollaboratoR - Kenneth MacLean

Done initially as single 1 hour workshops in Evening in spring/summer, combined as a 3 hour workshop at R/medicine in late August 2021 (workshops 24-25 Aug)
