### ISSUE TITLE
Adapt `retrieve_credential_mssql()` for odbc v 1.3.x package

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#336]
When the [odbc package moved from v1.2.3 to v 1.3.0](https://github.com/r-dbi/odbc/releases/tag/v1.3.0), the [`retrieve_credential_mssql()`](https://ouhscbbmc.github.io/REDCapR/reference/retrieve_credential.html) function stopped working (at least in our system).  The error message was 
```
Error in result_fetch(res@ptr, n) : index out of range
Warning message:
In DBI::dbClearResult(result) : Result already cleared)
```

In the meantime, we've been using v1.2.3.  I think I just found that limiting the returned record count to 1 fixes the issue for our specific function, which should retrieve only 0 or 1 record.

@ARPeters & @genevamarshall, will you please see if this works on your machines by installing the dev version of REDCapR and the newest odbc v1.3.2 on CRAN?

```r
remotes::install_github(repo="OuhscBbmc/REDCapR", ref = "dev")
```

This should be a better fix for https://github.com/OuhscBbmc/miechv-3/issues/2429

**Comment by genevamarshall** [comment]
I've updated odbc and the dev version of REDCapR and have not had issues pulling from or writing to REDCap in R.

**Comment by wibeasley** [comment]
There was an extra statement (ie, `select system_user`) that lived outside CREATE/END block for the stored procedure.  I guess I included it for debugging once, and never removed.  Removing it fixed the issue entirely, and didn't require the `n = 1` parameter workaround.  In hindsight it worked because odbc 1.3 had permission to ignore everything that came after the legit credential row.  

I'm still not sure why that state was returned to the user, considered it followed the `END`.

@genevamarshall  & @ARPeters, will you try the dev branch one more time? 

```r
remotes::install_github(repo="OuhscBbmc/REDCapR", ref = "dev")
```

If that works, please tell your teams to use the most recent version of odbc from CRAN, and the most recent REDCapR from GitHub.

```r
remotes::install_github(repo="OuhscBbmc/REDCapR")
```
