### ISSUE TITLE
Subset dataset issue

### ISSUE THREAD

**Issue by aas4120** [OuhscBbmc/REDCapR#338]
Hi,

When I used "redcap_read_oneshot" to import data from Redcap, the fields parameter did not work. The situation is that I would like to import a dataset with a few specified columns, some of them cannot be imported.

For example: 
In the whole dataset from my Redcap system, it contained a  tons of variable including "local_id"                  "redcap_event_name" , "visit_date_enroll" ,"gender" ,"race___1" ,"race___2" , "race___3" ,"race___4","race___5"                         "race___7", "race___8" , "ethnicityhispaniclatino" ,"yearsofeducation", etc.                     

I only wanted to obtain a dataset contained variables such as "local_id", "gender", "race__1", "race__2". 
`Demographics`<-redcap_read_oneshot(
                                    redcap_uri = uri,
                                    token      = token,
                                    fields=c("local_id", "gender", "race__1", "race__2"))$data

However, I can only get "local_id", and "gender". I do not know why I cannot get the rest of variables("race__1", "race__2").

Thanks for your time to take a look at this issue.

**Desktop :**
 - OS: Windows 10
 - REDCap version: 10.6.17 
 - REDCapR Version : 0.11.0

Best,

Jeff

**Comment by wibeasley** [comment]
Hey @aas4120, thanks for providing so much information to make it easy for others to understand.  It looks like `race` is a multiselect checkbox?  If so, try

```r
redcap_read_oneshot(
  redcap_uri = uri,
  token      = token,
  fields     = c("local_id", "gender", "race")
)$data
```

In other words, just `race` instead of `race___1` & `race___2`.  

BTW, REDCap uses three underscores between the variable (*e.g.*, race) and the checkbox index (*e.g.*, 1, 2, 3, ..., 8)

**Comment by aas4120** [comment]
Hi wibeasley,

Yes, the "race" is a multiselect checkbox.

Thanks for your time to solve this issue! I do appreciate it!

Best,

Jeff
