### ISSUE TITLE
Version 1.0.0 breaks `redcap_read` when used in a docker container.

### ISSUE THREAD

**Issue by ChemiKyle** [OuhscBbmc/REDCapR#350]
Release 1.0.0 has broken calls to `redcap_read` when called from a docker container.

Calls to `redcap_read` result in the following error:

```
Error in inherits(ds, \"data.frame\"): object 'ds' not found
```

We've narrowed the breakage down to commit b1e85c4f

I think it's this line, specifically the `kernel` object is probably different in a docker context:  
https://github.com/OuhscBbmc/REDCapR/blob/652c35c6c3233b06297cf362bc6306334314d6c0/R/redcap-read-oneshot.R#L261

We're currently updating our scripts to lock us to commit c5bce6a, prior to the use of `readr 2.0.0`, but if I get a free moment I will provide a minimal Dockerfile and R script to reproduce.

We see this using a container based on the `rocker/4.0.1` image, but also saw it in `rocker/4.1.0`.

___
Somewhat related, we've been making a generic ETL framework that relies on heavily on docker and REDCapR: https://github.com/ctsit/redcapcustodian/

Since you're presenting this package soon, I figured it would be worth mentioning :)

**Comment by wibeasley** [comment]
Thanks for being so thorough and tracking finding the breaking line/commit.  Can you doublecheck that readr 2.0.0 is installed correctly in the container (plus its dependencies)?  I added the call to `I()` to avoid warnings from vroom/readr.

readr/vroom doc: https://github.com/r-lib/vroom/blob/f9c5898009b1d872e0237ae4eb3801b9d0454aeb/R/vroom.R#L55-L56
```r
# Or directly from a string with `I()`
vroom(I("x,y\n1,2\n3,4\n"))
```

Will you try this branch?  https://github.com/OuhscBbmc/REDCapR/tree/gator-try-1

I stripped out the `I()` and [some other things](https://github.com/OuhscBbmc/REDCapR/commit/7471e7d8cd9ede7df6238a8ea002df37ee2da0ed) that should produce a better error message. Install it with 

```r
remotes::install_github("OuhscBbmc/REDCapR", ref = "gator-try-1")
```

**Comment by ChemiKyle** [comment]
Hi @wibeasley ,

I had just made you a minimal example when my power went out. I wasn't expecting such a fast response!

[rcr_docker_minimal.zip](https://github.com/OuhscBbmc/REDCapR/files/6871113/rcr_docker_minimal.zip)

Unzipping, setting `TOKEN` and `URI` in `test.R` and then running `test.sh` should be enough to reproduce the bug.

___

It's pretty close to 5 but I'll try targeting your branch for download and getting back to you.

**Comment by ChemiKyle** [comment]
[rcr_bug.zip](https://github.com/OuhscBbmc/REDCapR/files/9610447/rcr_bug.zip)

**Comment by wibeasley** [comment]
@ChemiKyle, at REDCapCon this week, I believe you said this was no longer a problem.  If something like this arises again, let's do a zoom call so you can walk me through debugging a docker instance.
