### ISSUE TITLE
Error in inherits(ds, "data.frame") : object 'ds' not found

### ISSUE THREAD

**Issue by ShinyboyB** [OuhscBbmc/REDCapR#351]
Hey guys,

I am working with REDcapR since April without any problems.
But I want to handover my project and run into the following problem:
My colleague gets with supposedly the same setting the error code above. I tride the troubleshooting with data hosted by the OUHSC BBMC. But is not working.
I'm using version 0.11.0 with following code: 
`df <- redcap_read_oneshot(redcap_uri = url,           
                                token = token, 
                                export_data_access_groups =T)$data`

I hope someone can help me to solve that problem.

kind regards,

Bernhard

**Comment by ShinyboyB** [comment]
ok this must be a local problem, because it is working on other machines.

**Comment by wibeasley** [comment]
@ShinyboyB, [version 1.0.0](https://github.com/OuhscBbmc/REDCapR/releases) has been on CRAN since late July.  I suggest making sure all packages are up-to-date, including REDCapR's dependencies.  [Especially readr 2.0](https://github.com/OuhscBbmc/REDCapR/issues/343).

**Comment by ShinyboyB** [comment]
@wibeasley thank your very much for your reply. I updated everything. But on this certain machine it is not working. I will reinstall R to see if we can fix the problem with that
