### ISSUE TITLE
Mimic @januz's dictionary with 35k variables

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#360]
@januz had a very very wide dataset that REDCap  had problems producing the CSV for.  But the JSON was well-formed.  The changes made in #335 work now on his machine, but we'd like to include a similar dictionary to detect any regression errors in the future.

I'll probably 
- [x] simulate it now with a big loop to spit out the csv dictionary, and then
- [x] throw in some flavor from his real dictionary (that shouldn't be public)

**Comment by wibeasley** [comment]
@januz, I used the adapted text that you approved.  If you'd like any other features in the dictionary, either start a new issue (and reference this one), or just add it to the code that generated the dictionary:

https://github.com/OuhscBbmc/REDCapR/blob/dev/inst/test-data/super-wide-3/generate-dictionary.R

**Comment by januz** [comment]
Sounds good. Thanks, @wibeasley!
