### ISSUE TITLE
Unexpected Behavior: validate_field_names errors for single character field names

### ISSUE THREAD

**Issue by daynefiler** [OuhscBbmc/REDCapR#367]
**Describe the behavior**: I have a RedCap database that includes single-character field names. With the current behavior of `validate_field_names`, I cannot query those fields. 

**Expected behavior**: I don't see a reason to require two-character field names; single character names should be permitted.

**Desktop (please complete the following information):**
 - REDCap version: 11.1.20
 - REDCapR Version: 1.0.0

**Comment by wibeasley** [comment]
Thanks a lot for identifying the limitation & loosening the restriction, @daynefiler.  The code looks good and the checks pass on the dev branch.  I'm pulling it into the main branch. (#369)
