### ISSUE TITLE
Include contributor emails

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#37]
Hi @thomasnwilson, @bard1536, @rparrish, and @johnaponte.  Thanks for the different ways you guys have improved to the REDCapR package.

You are already (or soon will be) added to the list of [contributors](https://github.com/OuhscBbmc/REDCapR/blob/31ffcb1e110a6a4a9513af70f316931c92679b4a/DESCRIPTION#L6-L9).  If you would like your email added to this list (and [within the reference manual](https://github.com/johnaponte/REDCapR/commit/8523e534f981e2b61c122ee5429dfb07f8c9dbff)), please tell me what address to use.

Remember your email address is on a public space, so I don't want to include something if you're not comfortable with it.  If you want a link to your faculty/personal/whatever page too, I'm happy to do that.

**Comment by wibeasley** [comment]
Anyone tell me if they want their email address added (including those who contributed after this issue was created)

**Comment by johnaponte** [comment]
Dear Will,
Yes, I would like my e-mail added.
Thanks and best regards
JJ

**Comment by wibeasley** [comment]
great @johnaponte.  Will you please tell me which email address you'd like included?  Thanks again for contributing code.

**Comment by rparrish** [comment]
Thanks Will. OK to use rparrish@flightweb.com for me.

-- 
Rollie Parrish
rparrish@flightweb.com
