### ISSUE TITLE
Flexible regex for token

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#370]
*Spun off from the comments in https://github.com/michalkouril/REDCapR/commit/9143b8551ae44b365df7a1d4211ace19bcbdb65f*

@maeon, cool.  I like it.  I have a similar approach where [LDAP/AD credentials are traded for REDCap tokens](https://ouhscbbmc.github.io/REDCapR/articles/SecurityDatabase.html).  But it sounds like your approach bundles it more seamlessly.

Your token format is consistent, correct?  Instead of turning off the check, would it work with your approach to allow the user to specify the regex?

We could add a `token_pattern` parameter with a default of `"^([0-9A-Fa-f]{32})(?:\\n)?$"`.  In the code executed in AWS, your user could pass something like `token_pattern = "^([0-9A-Fa-f]{128})(?:\\n)?$"`.

------

To people joining this thread, this won't weaken security because this regex has no role in authentication.  It simply notifies the user of a if their token doesn't look right, and therefore hopefully helps them diagnose the problem quicker.

**Comment by maeon** [comment]
Great! I like the token_pattern as a parameter approach. My token format is variable length base64 encoded -- so slightly more complicated but absolutely doable.

I'll just need the parameter specified once instead of with each function call -- such as env variable, global option, etc.

**Comment by wibeasley** [comment]
Another option is the regex pattern could accept both types of tokens.  Does anyone have a preference?

To accept both types of tokens, the parameter default would be something like (I'm guessing on the length).

```r
token_pattern = "^([0-9A-Fa-f]{32}|[0-9A-Za-z]{20})(?:\\n)?$"
```

**Comment by maeon** [comment]
I believe it make sense to default to the current REDCap token pattern and let user specify a custom one if the situation warrants it.

**Comment by wibeasley** [comment]
Cool.  I've rearranged your code a little.  I don't use environmental variables, so please write it so it works most naturally for you.  If you like it, please submit a PR.

```r  
pattern <- 
  if (Sys.getenv("REDCAP_TOKEN_PATTERN") != "") {
   Sys.getenv("REDCAP_TOKEN_PATTERN")
  } else {
    "^([0-9A-Fa-f]{32})(?:\\n)?$"
  }
```

Also, let me make sure I understand, "I'll just need the parameter specified once instead of with each function call -- such as env variable, global option, etc."  Is it because `sanitize_token()`  is called inside [20+ functions](https://github.com/OuhscBbmc/REDCapR/search?q=sanitize_token) and you don't want to the token pattern to all of them?

If so, one option would be for me to expand the [project object](https://github.com/OuhscBbmc/REDCapR/blob/main/R/redcap-project.R) to include all the methods (not just read & write).  Or maybe that's what you meant by "global option".  I haven't kept up with adding methods b/c no one seems to use the project object and I didn't want to duplicate all the tests unnecessarily.  But if the project object was used, the token pattern would be passed once initially and stored internally, then passed each time to a method.

**Comment by wibeasley** [comment]
@maeon & @michalkouril, see how you like this function and its documentation in this .  Tell me if there's something you'd like to change.,
