### ISSUE TITLE
Filtering based on multiple fields when calling `redcap_read()` does not seem to work

### ISSUE THREAD

**Issue by echaritos** [OuhscBbmc/REDCapR#379]
Filtering based von multiple fields when calling ` readcap_read() ` does not seem to work

**Expected behavior**: Filtering based on multiple filter possible. 

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - REDCap version REDCap 12.0.6
 - REDCapR Version 1.0.0

**Additional context**: 
```
redcap_read(redcap_uri="XXX", token="YYY", fields = c("record_id", "var2", "var3", "var4" ), filter_logic = c("[var2]=1")) #Works
redcap_read(redcap_uri="XXX", token="YYY", fields = c("record_id", "var2", "var3", "var4" ), filter_logic = c("[var3]=1","[var2]=1")) ##Does not work
```

Is it possible to use AND/OR/NOT logic when filtering?

**Comment by wibeasley** [comment]
I think you should be able to say and/or like a conventional statement.  Can you try this?  If it doesn't work, I can look more closely  in the next few days.

```r
...
filter_logic = "[var3]=1 and [var2]=1"
...
```

**Comment by echaritos** [comment]
doesn't seem to work.` filter_logic = "[var3]=1 and [var2]=1" `throws ```
 Error in redcap_read(redcap_uri = "XXX",  : 
  formal argument "filter_logic" matched by multiple actual arguments
```
Thank you for your help

**Comment by wibeasley** [comment]
That doesn't sound like an error thrown by REDCap or REDCapR.  It sounds like an error thrown by R itself.  Are you sure your not passing `filter_logic` twice in the same call?

```r
mean(x=1:5, x= 11:15)
## Error in mean(x = 1:5, x = 11:15) : 
##   formal argument "x" matched by multiple actual arguments
```

If not, can you start with the simplest call (again), and then add one argument at a time until the "matched by multiple..." error is returned?

**Comment by wibeasley** [comment]
@echaritos, I'm going to assume this was solved by eliminating one of the `filter_logic` arguments.  If you'd like, reopen with more information.
