### ISSUE TITLE
Unexpected Behavior: missing timestamp variable export

### ISSUE THREAD

**Issue by ctalbs** [OuhscBbmc/REDCapR#387]
**Describe the behavior**: I am exporting data from redcap using the following script:

```
df <- redcap_read_oneshot(
      redcap_uri = uri,
      token =token,
      raw_or_label = "label", # we want to use the labels we made in REDCap
      raw_or_label_headers = "label", # but we want the raw variable names that are easier to use
      export_survey_fields = TRUE,
      verbose = TRUE
      )$data
```

However this seems to be omitting a number of variables that are in datetime format. These variables are not limited in access in regards to my user or usergroup privs. If I export directly from redcap into CSV, these missing values are included in the appropriate format.

![image](https://user-images.githubusercontent.com/51867936/157281422-cd44ef70-f6f6-4cea-ba07-5b3b9130e8f3.png)

**Expected behavior**: Complete export of all variables.

**Desktop (please complete the following information):**
 - OS: W10
 - REDCap version: 10.5.2
 - REDCapR Version: 1.0.0

Thanks!

**Comment by wibeasley** [comment]
That's weird.  It's only a problem with datetimes?  

What is the output of this?  It's exporting only two variables, and [isn't trying to convert to any data type](https://ouhscbbmc.github.io/REDCapR/articles/workflow-read.html#specify-everything-is-a-character).

```r
desired_fields <- c("record_id", "first_test_date")
col_types <- readr::cols(.default = readr::col_character())
REDCapR::redcap_read(
  redcap_uri  = uri,
  token       = token,
  fields      = desired_fields,
  col_types   = col_types
)$data
```

**Comment by ctalbs** [comment]
Hi, thank you so much for response! I changed id label but here is output. Strange that it is changing to something with my control arms...

```
>     desired_fields <- c("guid", "first_test_date")
>     col_types <- readr::cols(.default = readr::col_character())
>     col_types
cols(
  .default = col_character()
)
>     REDCapR::redcap_read(
+       redcap_uri  = uri,
+       token       = token,
+       fields      = desired_fields,
+       col_types   = col_types
+     )$data
The data dictionary describing 208 fields was read from REDCap in 0.3 seconds.  The http status code was 200.                                           
24 records and 2 columns were read from REDCap in 0.3 seconds.  The http status code was 200.                                                           
Starting to read 24 records  at 2022-03-08 13:31:22.
Reading batch 1 of 1, with subjects 1 through 24 (ie, 24 unique subject records).
24 records and 2 columns were read from REDCap in 0.3 seconds.  The http status code was 200.                                                           
   guid redcap_event_name
1     1     event_1_arm_1
2     2     event_1_arm_1
3     3     event_1_arm_1
4     4     event_1_arm_1
5     5     event_1_arm_1
6     6     event_1_arm_1
7     7     event_1_arm_1
8     8     event_1_arm_1
9     9     event_1_arm_1
10   10     event_1_arm_1
11   11     event_1_arm_1
12   12     event_1_arm_1
```

**Comment by wibeasley** [comment]
Using the exact same token, does the field appear with [`REDCapR::redcap_metadata_read()`](https://ouhscbbmc.github.io/REDCapR/reference/redcap_metadata_read.html)?

----------------

@ctalbs, You've been really thorough, so these probably aren't the problem here.  If anyone else is following this thread because they encountered something similar, please ensure
1. the token is pointing to the correct project.
2. the url is pointing to a correct REDCap instance on your campus (*e.g.*, not a dev instance, or something like that).
3. the field name (*e.g.*, "first_test_date") is spelled exactly.
4. you have "Full Data Set" rights for export.
    ![image](https://user-images.githubusercontent.com/1372890/157694449-dc9f754d-36c7-4691-844a-736fd75985e2.png)

**Comment by ctalbs** [comment]
@wibeasley Thanks for your help! The plot thickens!

Using metadata_read() does return the missing the date fields that are not returned by read() or read_oneshot(). In the metadata frame that is returned these values do not appear to be obscure or protected compared to the other values that read() is returning.

**Comment by wibeasley** [comment]
Q1) Can you remove R & REDCapR from the equation?  In other words, does the field appear when you use the Playground or Postman (as described in the [Troubleshooting Vignette](https://ouhscbbmc.github.io/REDCapR/articles/TroubleshootingApiCalls.html#reading))?

Q2) Two posts ago, what did you mean by this?  Does this project have arms?  I can't image arms would interact with datetimes, but I guess it's one more possible problem

    > Strange that it is changing to something with my control arms...

**Comment by wibeasley** [comment]
@ctalbs, any progress?  Are the fields still missing?  Did the diagnostic suggestions in my previous post provide any useful info?

**Comment by wibeasley** [comment]
@ctalbs, I'm closing this issue.  Reopen the issue if it's still popping up.  If so, please answer those two questions in the March 22 post.

**Comment by gkaramanis** [comment]
Hi, and thanks for REDCapR!

I have encountered the same problem with missing timestamp variables:

The exported dataset from REDcap has 1368 columns with 33 timestamp variables.
redcap_read() returns 1326 columns with 0 timestamp variables
metadata_read() returns 1030 columns with 2 timestamp variables

I have tested the REDCap API in the Playground and it seems to work in general but I still get 1326 columns with no timestamps, both with my own and an admin token

The project I'm working with has arms

Is there anything else I could do for troubleshooting or more information you need?

**Comment by wibeasley** [comment]
@gkaramanis, I'm splitting this into a new issue: #447
