### ISSUE TITLE
Consider removing real token from documentation

### ISSUE THREAD

**Issue by pwildenhain** [OuhscBbmc/REDCapR#388]
Code located here: https://github.com/OuhscBbmc/REDCapR/blob/d60a02f4234000b5c4eb1fc55446b8ce67cf29c3/R/metadata-utilities.R#L57-L64

This is a real token (I tested it 😈 ), and prob shouldn't be in the package. The code was last touched 4-6 years ago, so it's understandable it flew under the radar this long 🙈 

I think replacing it with blank string, and leaving some nice comments telling the user to put in their own URL and token would be appropriate, still helpful, and safer

Happy to put in a PR for this if you agree

**Comment by wibeasley** [comment]
Thanks for bringing this up.  It is a real token to a fake/PHI-free project.  The REDCapR packages has about [30 example projects](https://github.com/OuhscBbmc/REDCapR/blob/main/inst/misc/example.credentials) used for a few dozen documentation examples and a few hundred [automated tests](https://github.com/OuhscBbmc/REDCapR/tree/main/tests/testthat).

Are you concerned by this, or does this change your mind?

**Comment by pwildenhain** [comment]
Oh I figured it was a fake project, my concern was more about if someone wanted to be really mean they could just hammer OUHSC with tons of requests, and you (or whoever's token that is) would get the blame

I could just be being paranoid so if you're not concerned about that then feel free to close it out 

I would also add that if you're not concerned about it, then maybe consider integrating that actual project into a lot more of the examples because I definitely see the utility of having a 'real' project

**Comment by wibeasley** [comment]
I keep an eye on the traffic, and so far it's been worth the trade off.  If someone started making trouble, I'd revoke those tokens and I guess move to short-lived instances on GitHub Actions.
