### ISSUE TITLE
Allow guess_max = Inf in redcap_read_oneshot()

### ISSUE THREAD

**Issue by eveyp** [OuhscBbmc/REDCapR#392]
In `readr` v2.0+, the `guess_max` argument can be set to `Inf` to use all of the data to determine the column type. Right now, it seems that the argument checking requires an integer so this option can't be used. 

Can that be changed to allow this option?

**Comment by wibeasley** [comment]
Thanks.  That's a good suggestion.

Any reason to change the value the default value of 1,000?  It sounds like you've read it already, but for convenience, here's readr's approach to `guess_max`: https://readr.tidyverse.org/articles/column-types.html.  And you're right, REDCapR uses 2.0.
