### ISSUE TITLE
Obtain Report ID from REDCap via API

### ISSUE THREAD

**Issue by liuc3k** [OuhscBbmc/REDCapR#393]
Hi,

I am just wonder is it possible to create a function to obtain "Report ID" from REDCap via API? Thanks!

**Comment by wibeasley** [comment]
I think I understand, but to make sure, can you provide a few details and an example?  

Does the REDCap server expose this feature?  If so, can you tell me your version?

**Comment by wibeasley** [comment]
Ok.  Tell me if that becomes a formal API function.

Consider describing the need in the [Suggestions For New Features & Enhancements](https://community.projectredcap.org/spaces/31/index.html) space of the community site.  If you don't have access to this link, your site's REDCap admin should.
