### ISSUE TITLE
rename file for `redcap_dag_export()`

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#402]
@joundso, a few followups to #382.  Will you please
1. rename "R/redcap-read-dag.R" to "R/redcap-dag-read.R".  If anyone is reviewing the file in GitHub, I want it to be obvious that you did most of the work (like the logging export function #383)
2.  Add yourself to the [DESCRIPTION](https://github.com/OuhscBbmc/REDCapR/blob/main/DESCRIPTION) file after Victor?
3. I've already added you & the function to [NEWS.md](https://github.com/OuhscBbmc/REDCapR/blob/main/NEWS.md)

If that's a hassle, I'm happy to do this.  Just send me your ORCID number so you're better identified.

**Comment by joundso** [comment]
@wibeasley Thank you very much for your work and please excuse me for not getting back to you in a while! Unfortunately I hardly get to code here at the moment. I hope that will change again soon. Thanks again for all "helping out"!
