### ISSUE TITLE
REDCap Cloud support

### ISSUE THREAD

**Issue by joelsand** [OuhscBbmc/REDCapR#403]
Hi there,

I'm trying to use this with a REDCap Cloud instance - is there any support for that or planned for a future version?

**Comment by wibeasley** [comment]
I haven't really thought about it, but I'm not opposed to it.  I've never used REDCap Cloud and don't have access to it.  Are the API signatures identical?  If not, a new package may make sense.  If so, what differences are involved (if any)?
