### ISSUE TITLE
new `redcap_metadata_coltypes()` function

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#405]
@pbchase had the great suggestion (2.5 years ago in #294) to expose a function like `get_col_types_from_metadata()`.    

> I think redcap_read() should use another new function, perhaps named get_col_types_from_metadata() that would generate the col_types vector from the metadata. The poor bastards that can't set leverage_metadata to true would then have the option to generate the col_types vector, mutate it and then use the mutated output.

Sorry I never made an issue and then forgot about it until now.  I like the idea and think it would help @SimpleAddress4390's [slog](https://github.com/nutterb/redcapAPI/issues/184#issuecomment-1212221198) expressed in https://github.com/nutterb/redcapAPI/issues/184.

In my group's OuhscMunge package, we have a few functions that receive a data.frame and spit out code to the console.  (See the package's [`readr_spec_aligned()`](https://ouhscbbmc.github.io/OuhscMunge/reference/readr_spec_aligned.html) and the [headstart utilities](https://ouhscbbmc.github.io/OuhscMunge/reference/headstart_utilities.html).)

To be tediously explicit here, this new function will
1. call [`redcap_metadata_read()`](https://ouhscbbmc.github.io/REDCapR/reference/redcap_metadata_read.html), and then
2. convert the `validation_name` values into text that follows the syntax of [readr col_types](https://readr.tidyverse.org/reference/cols.html) which will
3.  output readr code to the console, that can be 
4. pasted into an R file and assigned to a variable like `col_types`, that is 
5.  optionally modified before
6. being passed to the [existing `col_types`](https://github.com/OuhscBbmc/REDCapR/issues/258) argument of [`redcap_read()`](https://ouhscbbmc.github.io/REDCapR/reference/redcap_read.html)

When the function is passed the metadata's validation name/label (in the 3rd & 4th colunns), here are the [readr::col_types](https://readr.tidyverse.org/reference/cols.html) specified in the console (in step *b* above).  The #294 table is the starting point, but it's simplified following the observations & corrections from @pbchase & @nutterb.  For example both "date_mdy" and "date_ymd" use just `col_date()`, because that's how it's stored ymd in REDCap.

@pbchase, @nutterb, @SimpleAddress4390 and others, would this work with your workflows?  Any suggestions to make it better?

|      | [readr::col_types](https://readr.tidyverse.org/reference/cols.html) | validation_name          | validation_label                             |
|------|-----------------------------------------|--------------------------|--------------------------------------------- |
| :o:  | `col_character()`                       | alpha_only               | Letters only                                 |
| :o:  | `col_date()`                            | date_dmy                 | Date (D-M-Y)                                 |
| :o:  | `col_date()`                            | date_mdy                 | Date (M-D-Y)                                 |
| :o:  | `col_date()`                            | date_ymd                 | Date (Y-M-D)                                 |
| :o:  | `col_datetime("%Y-%m-%d %H:%M")`        | datetime_dmy             | Datetime (D-M-Y H:M)                         |
| :o:  | `col_datetime("%Y-%m-%d %H:%M")`        | datetime_mdy             | Datetime (M-D-Y H:M)                         |
| :o:  | `col_datetime("%Y-%m-%d %H:%M:%S")`     | datetime_seconds_dmy     | Datetime w/ seconds (D-M-Y H:M:S)            |
| :o:  | `col_datetime("%Y-%m-%d %H:%M:%S")`     | datetime_seconds_mdy     | Datetime w/ seconds (M-D-Y H:M:S)            |
| :o:  | `col_datetime("%Y-%m-%d %H:%M:%S")`     | datetime_seconds_ymd     | Datetime w/ seconds (Y-M-D H:M:S)            |
| :o:  | `col_datetime("%Y-%m-%d %H:%M")`        | datetime_ymd             | Datetime (Y-M-D H:M)                         |
| :o:  | `col_character()`                       | email                    | Email                                        |
| :o:  | `col_integer()`                         | integer                  | Integer                                      |
| :o:  | `col_character()`                       | mrn_10d                  | MRN (10 digits)                              |
| :o:  | `col_character()`                       | mrn_generic              | MRN (generic)                                |
| :o:  | `col_double()`                          | number                   | Number                                       |
| :o:  | `col_double()`                          | number_1dp               | Number (1 decimal place)                     |
| :o:  | `col_double()`                          | number_1dp_comma_decimal | Number (1 decimal place - comma as decimal)  |
| :o:  | `col_double()`                          | number_2dp               | Number (2 decimal places)                    |
| :o:  | `col_double()`                          | number_2dp_comma_decimal | Number (2 decimal places - comma as decimal) |
| :o:  | `col_double()`                          | number_3dp               | Number (3 decimal places)                    |
| :o:  | `col_double()`                          | number_3dp_comma_decimal | Number (3 decimal places - comma as decimal) |
| :o:  | `col_double()`                          | number_4dp               | Number (4 decimal places)                    |
| :o:  | `col_double()`                          | number_4dp_comma_decimal | Number (4 decimal places - comma as decimal) |
| :o:  | `col_double()`                          | number_comma_decimal     | Number (comma as decimal)                    |
| :o:  | `col_character()`                       | phone                    | Phone (North America)                        |
| :o:  | `col_character()`                       | phone_australia          | Phone (Australia)                            |
| :o:  | `col_character()`                       | postalcode_australia     | Postal Code (Australia)                      |
| :o:  | `col_character()`                       | postalcode_canada        | Postal Code (Canada)                         |
| :o:  | `col_character()`                       | postalcode_french        | Code Postal 5 caracteres (France)            |
| :o:  | `col_character()`                       | postalcode_germany       | Postal Code (Germany)                        |
| :o:  | `col_character()`                       | ssn                      | Social Security Number (U.S.)                |
| :o:  | `col_time("%H:%M")`                     | time                     | Time (HH:MM)                                 |
| :o:  | `col_time("%H:%M")`                     | time_mm_ss               | Time (MM:SS)                                 |
| :o:  | `col_character()`                       | vmrn                     | Vanderbilt MRN                               |
| :o:  | `col_character()`                       | zipcode                  | Zipcode (U.S.)                               |

**Comment by pbchase** [comment]
I like everything you wrote here. I have two thoughts to make this more robust and a little bit more flexible. Inevitably, there will be validation types that are unknown to this function. The function needs to not fail when it encounters one. The easy behavior is to type columns with unknown validation types as character and throw a warning. An alternative option would be to guess the data types in those columns.

The other feature I think might be useful is the ability to specify those unknown validation types and the resulting column type. This would allow the programmer to respond to the warnings, and set the column types correctly in a streamlined workflow.
