### ISSUE TITLE
Incorrect guess_type documentation

### ISSUE THREAD

**Issue by BioStatMatt** [OuhscBbmc/REDCapR#411]
At the line referenced below, the help file says "If false, \code{\link[readr:read_delim]{readr::read_csv()}} guesses the intended data type for each column." However, this is opposite the actual behavior. It should read "If **true**, \code{\link[readr:read_delim]{readr::read_csv()}} guesses the intended data type for each column."

https://github.com/OuhscBbmc/REDCapR/blob/b3a107f1e4e997e017a404496bf8fb53b87789a6/man/redcap_read_oneshot.Rd#L121

**Comment by wibeasley** [comment]
oops.  Good catch, @BioStatMatt. Thanks.

**Comment by BioStatMatt** [comment]
We're making good use of REDCapR. Happy to help. Thx.
