### ISSUE TITLE
vignette for pulling repeated & longitudinal

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#417]
I'm getting a lot of questions how to do it with REDCapR

* rendered: https://ouhscbbmc.github.io/REDCapR/articles/longitudinal-and-repeating.html
* source: https://github.com/OuhscBbmc/REDCapR/blob/HEAD/vignettes/longitudinal-and-repeating.Rmd

**Comment by wibeasley** [comment]
@skadauke, @rsh52, @ezraporter, during REDCapCon I got a better feel for how REDCapTidieR and REDCapR best serve the different scenarios and users.  I wrote my ideas in the middle third of this vignette.  What do you think of this document?  Would you like to write any it, especially the parts that explicitly involve REDCapTidieR?

This is the section that is most subjective, and would like to know what you think.  And if we ever get ambitious enough for a manuscript, this is probably one of the key points.

![image](https://user-images.githubusercontent.com/1372890/192929012-a57c098d-d6ae-4d7f-a735-76d84697be94.png)

**Comment by skadauke** [comment]
Another key point to use REDCapR is if you want to write data to a database. 

I thought more about implementing `events`, `fields`, and `records` in `REDCapTidieR` but think now that we will probably leave these alone, and instead focus on creating useful error messages.

So another key point may be to use REDCapTidieR if you're new to analyzing REDCap data.

**Comment by skadauke** [comment]
I like the edits in the commit!
