### ISSUE TITLE
extra handle passed to `kernel_api()`

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#429]
suggested by @brandonpotvin in a meeting after REDCapCon

**Comment by brandonpotvin** [comment]
@wibeasley all three functions below are working as expected.
redcap_metadata_read()
redcap_read()
redcap_read_oneshot()

**Comment by wibeasley** [comment]
- [x] `redcap_read()`
- [x] `redcap_read_oneshot()`
- [ ] `redcap_read_oneshot_eav()`
- [ ] `redcap_write()`
- [ ] `redcap_write_oneshot()`
- [ ] `redcap_delete()`
- [ ] `redcap_report()`
- [ ] `redcap_download_file_oneshot()`
- [ ] `redcap_upload_file_oneshot()`
- [ ] `redcap_arm_export()`
- [ ] `redcap_dag_read()`
- [ ] `redcap_download_instrument()`
- [ ] `redcap_event_instruments()`
- [ ] `redcap_instruments()`
- [ ] `redcap_log_read()`
- [ ] `redcap_metadata_coltypes()`
- [x] `redcap_metadata_read()`
- [ ] `redcap_metadata_write()`
- [ ] `redcap_next_free_record_name()`
- [ ] `redcap_project_info_read()`
- [ ] `redcap_survey_link_export_oneshot()`
- [ ] `redcap_users_export()`
- [ ] `redcap_variables()`
- [ ] `redcap_version()`

**Comment by wibeasley** [comment]
@brandonpotvin, I've finished adding this parameter to all the functions (and its connection to `kernel_api()`).  All the existing tests still pass, but of course I can't replicate your institution's environment.  I guess I'll feel alright if you spot check a few more and give me the green light.  (Make sure you pull from GitHub again.)

**Comment by brandonpotvin** [comment]
@wibeasley I have tried most of the functions and all are working successfully.  You have the green light to commit as far as I am concerned.
