### ISSUE TITLE
explicitly specify `httr::POST()`'s value for `encode`

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#436]
related #429 & to @brandonpotvin's implicit suggestion, REDCapR should be tighter with [`httr::POST()`](https://httr.r-lib.org/reference/POST.html)'s `encode` parameter.  Right now, it uses httr's default of "multipart".  Looking at some things closely (like the API playground & httr documentation), it looks like most (but not all) should be "form".

This hasn't made a difference with any scenarios that I'm aware of.  But I'd like to standardize now, since some institutions are starting unconventional approaches.  I feel like following the API playground keeps more people centered.

**Comment by wibeasley** [comment]
@brandonpotvin, this shouldn't be noticeable to you.  But if you notice something weird/breaking in future cases, let's revisit this issue first.

**Comment by brandonpotvin** [comment]
@wibeasley, everything seems to be working as expected. I will let you know if I find something. Thanks.
