### ISSUE TITLE
Datetime variables aren't exported with a project w/ arms

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#447]
Posted by @gkaramanis in #387:

---------

>Hi, and thanks for REDCapR!
>
>I have encountered the same problem with missing timestamp variables:
>
>The exported dataset from REDcap has 1368 columns with 33 timestamp variables.
redcap_read() returns 1326 columns with 0 timestamp variables
metadata_read() returns 1030 columns with 2 timestamp variables
>
>I have tested the REDCap API in the Playground and it seems to work in general but I still get 1326 columns with no timestamps, both with my own and an admin token
>
>The project I'm working with has arms
>
>Is there anything else I could do for troubleshooting or more information you need?
>
> It seems to be an API issue, not related to REDCapR, right?

_Originally posted by @gkaramanis in https://github.com/OuhscBbmc/REDCapR/issues/387#issuecomment-1278990805_

**Comment by gkaramanis** [comment]
The project is longitudinal with automated surveys, the datetime variables are created automatically when a study participant completes a survey.

I will create another project on the same server and see if the problem persists and, in that case, provide you with the xml file, thank you!

**Comment by gkaramanis** [comment]
So, it seems there is no issue after all. I just found out about the exportSurveyFields flag in the API documentation and I get all the timestamps when I set it to TRUE in redcap_read(). I think you can close the issue, thanks a lot for helping a noob out :)
