### ISSUE TITLE
replay logs

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#450]
I need to use a project's log to reconstruct the dataset.  Someone accidentally clobbered a lot of values.  @pbchase  or anyone else, are you aware of something recent that does this?  I ddint' see any hits in the EM repo.  I saw @123andy's [plugin from 2016](https://community.projectredcap.org/questions/5278/plugin-that-replay-sql-command.html) (any updates, @123andy?).

I think the steps should be
1. [Read logs from REDCap](https://ouhscbbmc.github.io/REDCapR/reference/redcap_log_read.html) 
2. translate the values to an R data.frame (this is mostly what I have to write)
3. allow the user to filter what records are replayed (eg, based on user, datetime, etc) with conventional R functions
4. write to REDCap (maybe in an EAV format, instead of flat).  This probably should be to an empty project, in case someone wrote bad values during the clobbering.

This needs to happen today, but I'll come back to this to make step 2 more reusable for others.

cc: @DavidBard

**Comment by pbchase** [comment]
No, I've never heard of any code that does that. Everybody talks about how it's possible, but no one has ever told me they actually did it.

**Comment by wibeasley** [comment]
In order to meet the deadline yesterday, I had to avoid the API because it didn't contain enough info.  For example the API doesn't return the event name/id --even though it's in the download version (I'm drafting a request in  Community right now).

This worked for yesterday:
1. in DBeaver (or PHPMyAdmin) pulled rows meeting a certain criteria
2. in R:
    1. imported the csv 
    2. did some more filtering
    3. ordered by the primary key (or time)
    4. `gsub`ed a lot of sql text, such as crosswalking to the new pid & event_ids
    5. prepped the sql text, like adding a blank line in between each `insert`/`update`/`delete` command.  (For some reason, MariaDB or DBeaver didn't like consecutive lines!?)
    6. saved the sql as a single text file
3. opened the sql file in DBeaver and executed.

If the API call can add more info, I'll add a REDCapR function to help with this.

**Comment by pbchase** [comment]
@wibeasley, I wouldn't expect the API to provide the data you need any time soon. I always assumed  the task would require a query of the DB backend.

This work sounds like something that could be turned into a reusable and useful function on our project [redcapcustodian](https://github.com/ctsit/redcapcustodian). I think your use of DBeaver could be replaced by DBPlyr queries in R to allow a continuous pipeline to create the importable dataset or executable SQL file. 

Could you share the code you wrote here or in an issue on REDCap Custodian? I understand it is probably ugly, but I expect it would still provide value to the next person who needed to do this. As that next person might be me, I am eager to not reinvent anything.

**Comment by wibeasley** [comment]
Here's the project-specific code.  The main this to change for your project is the old & new values for `project_id` and `event_id`.  I think there's gotta be a better way with `ds_event_crosswalk` and something like [`purrr::reduce_2()`](https://purrr.tidyverse.org/reference/reduce.html).


```r
rm(list = ls(all.names = TRUE)) # Clear the memory of variables from previous run. This is not called by knitr, because it's above the first chunk.

# ---- load-sources ------------------------------------------------------------
# Call `base::source()` on any repo file that defines functions needed below.  Ideally, no real operations are performed.

# ---- load-packages -----------------------------------------------------------
# Attach these packages so their functions don't need to be qualified: http://r-pkgs.had.co.nz/namespace.html#search-path

# Import only certain functions of a package into the search path.
import::from("magrittr", "%>%")

# Verify these packages are available on the machine, but their functions need to be qualified: http://r-pkgs.had.co.nz/namespace.html#search-path
requireNamespace("readr"        )
requireNamespace("tidyr"        )
requireNamespace("dplyr"        ) # Avoid attaching dplyr, b/c its function names conflict with a lot of packages (esp base, stats, and plyr).
requireNamespace("rlang"        ) # Language constructs, like quosures
requireNamespace("testit"       ) # For asserting conditions meet expected patterns/conditions.
requireNamespace("checkmate"    ) # For asserting conditions meet expected patterns/conditions. # remotes::install_github("mllg/checkmate")
# requireNamespace("odbc"         ) # For communicating with SQL Server over a locally-configured DSN.  Uncomment if you use 'upload-to-db' chunk.
requireNamespace("OuhscMunge"   ) # remotes::install_github(repo="OuhscBbmc/OuhscMunge")
# requireNamespace("REDCapR"      ) # remotes::install_github(repo="OuhscBbmc/REDCapR")

# ---- declare-globals ---------------------------------------------------------
# Constant values that won't change.
config      <- config::get(file = "inst/config.yml")
directory   <- "P:/shared-drive"
path_in     <- fs::path(directory, "redcap_log_event.csv")
path_out    <- fs::path(directory, "to-replay.sql")

users_exclude <- c("hank", "dean", "brock")

# ds_event_crosswalk <-
#   tibble::tribble(
#     ~event_id_old , ~event_id_new,
#     "12966"       , "13810", # Study Start
#     "13344"       , "13811", # Week 1
#     "13345"       , "13812", # Week 2
#     "13346"       , "13813", # Week 3
#     "13347"       , "13814"  # Week 4/Study End
#   )

# OuhscMunge::readr_spec_aligned(path_in)
col_types <- readr::cols_only(
  `log_event_id`    = readr::col_integer(),
  # `project_id`      = readr::col_integer(),
  # `ts`              = readr::col_character(),
  `user`            = readr::col_character(),
  # `page`            = readr::col_character(),
  `event`           = readr::col_character(),
  `sql_log`         = readr::col_character(),
  `pk`              = readr::col_character(),
  `event_id`        = readr::col_integer(),
  `data_values`     = readr::col_character(),
  `description`     = readr::col_character(),
  # `change_reason`   = readr::col_logical()
)

# ---- load-data ---------------------------------------------------------------
ds <- readr::read_csv(path_in   , col_types = col_types)
# readr::problems(ds0)
rm(path_in, col_types)

# ---- tweak-data --------------------------------------------------------------
# OuhscMunge::column_rename_headstart(ds) # Help write `dplyr::select()` call.

# ---- prep-sql ----------------------------------------------------------------
# Further filter & sort to isolate the relevant sql
sql1 <-
  ds |>
  dplyr::select(    # `dplyr::select()` drops columns not included.
    log_event_id,
    user,
    sql_log,
    # pk,
    # event_id,
    # data_values,
    # description,
  ) |>
  dplyr::filter(!(user %in% users_exclude)) |>
  dplyr::arrange(log_event_id) |> # Super important to replay the logs in the correct order
  dplyr::pull(sql_log)

# ---- replace-event-id --------------------------------------------------------
# Order the regexes from most to least specific
sql2 <-
  sql1 %>%
  gsub("values \\(2982, 12966" , "values (3210, 13810"   , ., ignore.case = TRUE) %>% # for insert statements
  gsub("values \\(2982, 13344" , "values (3210, 13811"   , ., ignore.case = TRUE) %>% # for insert statements
  gsub("values \\(2982, 13345" , "values (3210, 13812"   , ., ignore.case = TRUE) %>% # for insert statements
  gsub("values \\(2982, 13346" , "values (3210, 13813"   , ., ignore.case = TRUE) %>% # for insert statements
  gsub("values \\(2982, 13347" , "values (3210, 13814"   , ., ignore.case = TRUE) %>% # for insert statements
  gsub("project_id = 2982"     , "project_id = 3210"     , ., ignore.case = TRUE) %>%# for insert statements
  gsub("select distinct '2982'", "select distinct '3210'", ., ignore.case = TRUE) %>%
  gsub("event_id = 12966"      , "event_id = 13810"      , ., ignore.case = TRUE) %>%
  gsub("event_id = 13344"      , "event_id = 13811"      , ., ignore.case = TRUE) %>%
  gsub("event_id = 13345"      , "event_id = 13812"      , ., ignore.case = TRUE) %>%
  gsub("event_id = 13346"      , "event_id = 13813"      , ., ignore.case = TRUE) %>%
  gsub("event_id = 13347"      , "event_id = 13814"      , ., ignore.case = TRUE)

# Inspect in the console
cat (sql2, sep = "\n--------\n")
# sql2[1]

# Within a cell, replace one line break with two
sql2 <- gsub(";\\n(?=\\w)", ";\n\n", sql2, perl = TRUE)
# sql2[1]

# At the end of a cell, add a semicolon and two line breaks
sql2 <- paste0(sql2, ";\n\n")
# sql2[1]

# sql2[140]
# ---- verify-values -----------------------------------------------------------
# Sniff out problems
# OuhscMunge::verify_value_headstart(ds)

# Make sure that the old pid and old event_ids no longer appear
testit::assert(!any(grepl("\\b2982\\b" , sql2))) # The old pid
testit::assert(!any(grepl("\\b12966\\b", sql2))) # One of the old event_ids
testit::assert(!any(grepl("\\b13344\\b", sql2))) # One of the old event_ids
testit::assert(!any(grepl("\\b13345\\b", sql2))) # One of the old event_ids
testit::assert(!any(grepl("\\b13346\\b", sql2))) # One of the old event_ids
testit::assert(!any(grepl("\\b13347\\b", sql2))) # One of the old event_ids

# ---- save-to-disk ------------------------------------------------------------
readr::write_lines(sql2, path_out)
```

**Comment by wibeasley** [comment]
As a minor tweak, I updated the *replace-event-id* chunk.  I think this manual-ish approach is best if there are 2-20 event ids to replace.  If there are hundreds (which were more common before REDCap's introduction of repeating measures a few years ago), I'd probably add a layer before this to dynamically create `ds_regex`.

```r
# ---- replace-event-id --------------------------------------------------------
# Order the regexes from most to least specific
ds_regex <-
  tibble::tribble(
    ~pattern                , ~replace,
    "\\bvalues \\(2982, 12966\\b"   , "values (3210, 13810"   , # for insert statements
    "\\bvalues \\(2982, 13344\\b"   , "values (3210, 13811"   , # for insert statements
    "\\bvalues \\(2982, 13345\\b"   , "values (3210, 13812"   , # for insert statements
    "\\bvalues \\(2982, 13346\\b"   , "values (3210, 13813"   , # for insert statements
    "\\bvalues \\(2982, 13347\\b"   , "values (3210, 13814"   , # for insert statements
    "\\bproject_id = 2982\\b"       , "project_id = 3210"     , # for insert statements
    "\\bselect distinct '2982'"     , "select distinct '3210'",
    "\\bevent_id = 12966\\b"        , "event_id = 13810"      ,
    "\\bevent_id = 13344\\b"        , "event_id = 13811"      ,
    "\\bevent_id = 13345\\b"        , "event_id = 13812"      ,
    "\\bevent_id = 13346\\b"        , "event_id = 13813"      ,
    "\\bevent_id = 13347\\b"        , "event_id = 13814"
  )

for (i in seq_len(nrow(ds_regex))) {
  print(ds_regex$pattern[i])
  sql <-
    gsub(
      pattern     = ds_regex$pattern[i],
      replacement = ds_regex$replace[i],
      x           = sql,
      perl        = TRUE,
      ignore.case = TRUE
    )
}

# Inspect in the console
cat (sql, sep = "\n--------\n")
# sql[1]

# Within a cell, replace one line break with two
sql <- gsub(";\\n(?=\\w)", ";\n\n", sql, perl = TRUE)
# sql[1]

# At the end of a cell, add a semicolon and two line breaks
sql <- paste0(sql, ";\n\n")
```

I requested two features that could help in the future
* [include `redcap_event_name` and repeated fields in log](https://community.projectredcap.org/questions/136486/include-redcap-event-name-and-repeated-fields-in-l.html)
* [Include `sql_log` field in the exported logs](https://community.projectredcap.org/questions/136494/include-sql-log-field-in-the-exported-logs.html)

**Comment by wibeasley** [comment]
@pbchase, tell me if you'd like any of this in your package.  Before your post, I was considering a vignette that showed those four steps (in this issue's original post).  So far this only works if you replay it in a fresh/empty project (because it doesn't erase bad values that shouldn't even be a record in `redcap_data`.  If you, @chemikyle, or anyone else has more ambitious, I'm happy to help.

**Comment by pbchase** [comment]
If you want to write the vignette, go ahead and write the vignette. I'll go make an issue right now to write some code based on this issue, we won't be able to get to this for awhile. 

I think your approach is interesting, I would not have replayed the SQL, but I think this might be the smartest approach.  I have one thought that might reduce the coding burden. Your `ds_regex` and the for loop that applies it to the SQL test looks hard to write.

What if you used SQLite as a translator from the SQL log to a dataframe?  Extract the SQL log content but don't translate it at all. Create an in memory redcap_data table. Write the SQL into it. Read the data back out of the in memory redcap_data. pivot it to get wide data. 

That produces something that might be importable into REDCap. Every step above could be executed in a single function.

If you need to edit the data in any way you can now do it with standard dplyr. I always find that easier. Maybe you still need to make a tibble of ID transformations and apply it, but perhaps you can do the translation algorithmically.

Would that approach have simplified your problem?

**Comment by wibeasley** [comment]
Ahh, use the MariaDB SQL to populate a SQLite table, then read it into dplyr, and finally import to REDCap with the API?  That enver occurred to me.  I like how it produces log entries (even if they reflect the API user, not the original user); my approach above produces zero log records.  

I wasn't planning to use the `sql_log` field, but the stuff coming out of the API was either missing stuff, or difficult to parse reliably.  For example the event name is just part of the string.  It's kinda easy to translate to the event_id, but tough to be sure that the the event name wasn't also inside a cell's contents.  Similarly, I never found a regex that would correctly identify if a comma was inside a cell (delimited by single quotes), or was delimiting a new eav row.

**Comment by pbchase** [comment]
> Ahh, use the MariaDB SQL to populate a SQLite table...

A nod is due to @ChemiKyle who taught me the wonders of the in-memory SQLite table. The differing DDL can trip you up in some cases, but that would not be of much concern in this case.

**Comment by 123andy** [comment]
Hi Will,

Sorry I didn't see this.  I've used our per-record mysql log plugin to replay records and recover data but nothing more than that.

-a
________________________________

**Comment by pbchase** [comment]
> A nod is due to @ChemiKyle who taught me the wonders of the in-memory SQLite table. The differing DDL can trip you up in some cases, but that would not be of much concern in this case.

I'll update this idea to suggest Duck DB over SQLite. It has richer data types. I'm not sure if its SQL syntax is closer to MySQl, but, with richer data types, I think that is likely.
