### ISSUE TITLE
small updates jumping from v12.5.5 to v13.1.0

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#459]
- [x] `redcap_dag_read()`: new `data_access_group_id` field introduced maybe in [13.1.0](https://community.projectredcap.org/articles/13/index.html)
- [x] `redcap_users_export()`: new `mycap_participants` field introduced maybe in [13.0.0](https://community.projectredcap.org/articles/13/index.html)

cc: @ezraporter & @rsh52

**Comment by rsh52** [comment]
Thanks, this will be good to keep in mind when we implement [DAG support](https://github.com/CHOP-CGTInformatics/REDCapTidieR/issues/57) in one of the REDCapTidieR features.
