### ISSUE TITLE
Feature request: Support for exportBlankForGrayFormStatus in redcap_read functions

### ISSUE THREAD

**Issue by yeamank** [OuhscBbmc/REDCapR#473]
Hi there,

I'm wondering if there are any plans to support the exportBlankForGrayFormStatus parameter in REDCapR's read functions. We have quite a few use cases at our institution that would warrant this. I feel that I read through the REDCapR documentation thoroughly and did not see any support for this, but apologies if I'm incorrect and this is already supported.

Cheers,
Kiley

**Comment by yeamank** [comment]
I just took a look at the GitHub repo and noticed redcap_read does have a parameter for this in the function. The documentation for REDCapR doesn't show the parameter, which is why I incorrectly assumed this wasn't a feature. My apologies.

**Comment by wibeasley** [comment]
Hi @yeamank, I kept meaning to come back for this.  I assume you saw the `blank_for_gray_form_status` parameter in [`redcap_read()`](https://ouhscbbmc.github.io/REDCapR/reference/redcap_read.html).  Does that meet your needs?

**Comment by yeamank** [comment]
Hi @wibeasley, thanks so much for following up. Yes, I saw the blank_for_gray_form_status parameter here in GitHub so I installed the dev version and it works perfectly. Not sure if I was using an outdated version or if the version on CRAN doesn't have this parameter, but regardless I'm relieved I don't need to find another work around. Thanks again!
