### ISSUE TITLE
Potential Breaking Change in REDCap 13.4.3

### ISSUE THREAD

**Issue by nutterb** [OuhscBbmc/REDCapR#474]
I've heard some reports that in REDCap 13.4.3, there have been a lot of new errors in various packages trying to access the API. It seems to have affected R, python, ruby, etc.

The crux of the issue is how vectors are being passed to the API. paste0(..., Collapse=",") will not work anymore.

See https://github.com/nutterb/redcapAPI/blob/main/R/vectorToApiBodyList.R for a solution that deals with this. This will affect anything that the API designates should be passed as an array

**Comment by wibeasley** [comment]
yikes, thanks for the heads up.  I'll update and check it out.

**Comment by wibeasley** [comment]
@nutterb, is this a pre-release version?  I don't see 13.4.3 on the standard download page.

![image](https://user-images.githubusercontent.com/1372890/228891202-3d94cf31-4943-482a-8a6b-a2661369e866.png)

**Comment by nutterb** [comment]
Interesting. This happened when Vanderbilt went to 13.4.3. but they may be on some kind of inside track. Maybe this wont be a problem by the time it's available to you? 

What I do know is that some methods haven't ever worked with that formatting. I have had problems with exportArms and deleteArms. I think exportFieldChoice mapping required the different formatting, too, I think.

**Comment by wibeasley** [comment]
To confirm to anyone listening, today's upgrade on OU's server (to 13.4.10) had some of these problems.  I'm working on it now.  

(@nutterb, thanks for the heads up.  It was nice having knowing I had to schedule time to upgrade REDCapR after upgrading the server.)

**Comment by wibeasley** [comment]
I think we're clear on the collapsed vectors.  Things did have to change a little in #477 & #478.

**Comment by wibeasley** [comment]
For those with access to the Community site, read about this issue here: <https://redcap.vanderbilt.edu/community/post.php?id=202055>
