### ISSUE TITLE
investigate broken GitHub Actions

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#475]
This problem popped up with @pwildenhain's #472 PR, but was unrelated to any changes to the R code (I presume).

**Comment by wibeasley** [comment]
@pwildenhain, I think I found the problem: "! `dags` must be size 25 or 1, not 0."  This is fixed with b37890edce479d7b35fb465d2f9ae865aa1cce34, which uses `grepl()` instead of `grep()`.  I bet that's what you meant.  Tell me if I'm wrong.

![image](https://user-images.githubusercontent.com/1372890/232840839-89404322-af74-42cc-8909-93438c9abca2.png)

https://github.com/OuhscBbmc/REDCapR/actions/runs/4315974347/jobs/7577684696

**Comment by pwildenhain** [comment]
Thanks for fixing that!
