### ISSUE TITLE
Release REDCapR 1.2.0 --replaced issue

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#479]
Prepare for release:

* [x] `git pull`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_REDCapR.html)
* [x] Check if any deprecation processes should be advanced, as described in [Gradual deprecation](https://lifecycle.r-lib.org/articles/communicate.html#gradual-deprecation)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] Update `cran-comments.md`
* [x] `git push`
* [ ] ~~Draft blog post~~

Submit to CRAN:

* [x] `usethis::use_version('minor')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] `git push`
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version()`
* [ ] `git push`
* [ ] ~~Finish blog post~~
* [ ] ~~Tweet~~
* [ ] ~~Add link to blog post in pkgdown news menu~~

REDCap-specific

- [ ] maybe update any posts on <community.projectredcap.org>

**Comment by wibeasley** [comment]
I'll wait a day or two for @RaymondBalise to review & accept https://github.com/RaymondBalise/tidyREDCap/pull/61.

**Comment by ravichowdhury88** [comment]
Any update to this release?

**Comment by wibeasley** [comment]
ugg, I let this slide.  I need to build the tests for @BlairCooper's PR #507, and then I'll restart the submission process.

**Comment by wibeasley** [comment]
replaced by #536
