### ISSUE TITLE
Unexpected Behavior: `redcap_event_instruments` does not return all arms by default

### ISSUE THREAD

**Issue by januz** [OuhscBbmc/REDCapR#482]
**Describe the behavior**:

I feel like a better default behavior for `REDCapR::redcap_event_instruments()` would be to return event-form mappings for all arms instead of for arm 1. Additionally, I was expecting that I could specify all arms as a character, e.g., `arms = c("1", "2", "3")` but this also only returns mappings for arm 1, i.e., one seems to only be able to export mappings for one arm at a time.

**Expected behavior**:

Default behavior should be like `redcapAPI::exportMappings()`, i.e., return mappings for all arms. If a user specifies a specific arm or a vector of selected arms, mapping for this / those arm(s) should be returned.

**Desktop (please complete the following information):**

 - OS: UNIX, Mac
 - REDCapR: Version ‘1.1.9005’

**Comment by wibeasley** [comment]
@januz, does this work like you want now?

**Comment by januz** [comment]
@wibeasley Sorry for the late reply and generally not having been in contact about the other issue we were talking about (unfortunately, work has been and continues to be crazy...). I just tested the new version and it works as expected. Thanks so much for implementing this!
