### ISSUE TITLE
BiocCheck

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#497]
@gabrielodom & @RaymondBalise suggested I also use the [BiocCheck](https://bioconductor.org/packages/BiocCheck/) package, in addition to lintr & goodpractice.  It's got some false positives (especially if I'm not submitting REDCapR to Bioconductor).  But it's got some good ones missed by lintr & goodpractice:

- [x] ~~NOTE: Avoid system() ; use system2()~~
- [x] NOTE: Avoid the use of 'paste' in condition signals
- [x] NOTE: 'sessionInfo' not found in vignette(s)
- [x] ~~WARNING: Empty or missing \value sections found in man pages.~~
    * I checked all 37 places in the Rd files with "value{".  All had content inside

**Comment by gabrielodom** [comment]
I personally like the package, but it's VERY opinionated. As you mentioned above, many of the things it complains about will not apply to your packages.
