### ISSUE TITLE
R CMD check ERROR

### ISSUE THREAD

**Issue by hadley** [OuhscBbmc/REDCapR#63]
I see

```
checking tests ... ERROR
Running the tests in ‘tests/test-all.R’ failed.
Last 13 lines of output:
                 character()
             else names(CURLcodeValues)[i]
         }
         typeName = gsub("^CURLE_", "", typeName)
         fun = (if (asError) 
             stop
         else warning)
         fun(structure(list(message = msg, call = sys.call()), class = c(typeName, "GenericCurlError", 
             "error", "condition")))
     }(35L, "Unknown SSL protocol error in connection to bbmc.ouhsc.edu:-9800", TRUE)
  
  Error: Test failures
  Execution halted
```

and I'm not sure what's causing the problem.

**Comment by hadley** [comment]
Here are the full test suite results:

```
Create Batch Glossary : .........
FileOneshot : ..1..2..3
Metadata Read : 456789
Metadata Utilities : ..
Project Object : ..a..b
Read Batch : cdefghi
Read Oneshot : jklmno
Validate data frame for writing to REDCap : ........
Write Batch : ..p..q..r..s
Write Oneshot : ..t..u..v..w
```

They're all failing with the same SSL error.

**Comment by wibeasley** [comment]
Thanks.  This check must have run during the server's maintenance window; the campus IT dept has been making a lot of changes recently.  The relevant tests are preceded with `testthat::skip_on_cran()` (I think I included those checks a few days after they were available in testthat).

I think this means you shouldn't get hassled by CRAN if their checks run during another maintenance window.  I'm happy to follow a different approach if there's a better one.
