### ISSUE TITLE
Calendar and Log Data

### ISSUE THREAD

**Issue by jtwinn** [OuhscBbmc/REDCapR#97]
Any plans to add capacity to pull log and calendar data?

**Comment by wibeasley** [comment]
Hi @jtwinn.  I wasn't planning on it, but can add it if someone would use it.

Are these new API features?  I don't see them in the list for our current version (6.0.2; see below).  But we're planning to upgrade soon.

![image](https://cloud.githubusercontent.com/assets/1372890/9768735/2961e66a-56eb-11e5-8a01-9d006dd314da.png)

**Comment by haozhu233** [comment]
@wibeasley As far as redcap 6.6.2 (updated in June, 2015), I don't see a log export option on the list but it seems like they did add a few more options since 6.0.2. Maybe they will add this feature in the future?

![capture](https://cloud.githubusercontent.com/assets/7014590/9769030/71abcd0a-56f5-11e5-9016-5883f2b918c0.PNG)

**Comment by nutterb** [comment]
I also don't recall there being an option to export the log. The list @haozhu233 has posted doesn't see to show a calendar option either (unless I'm missing it).  These may be features to ask about on the REDCap Google Group.

**Comment by jtwinn** [comment]
Thanks. After some digging I've been told that it's "low priority."  How else are we supposed to link the data to entry person? Many thanks for your responses.

**Comment by wibeasley** [comment]
I'm a little disappointed.  I was hoping there was a new API call to retrieve calendar data for one of our big projects.  Here's what we do:

We execute this SQL code, and read directly from MySQL through ODBC.  That dataset's later merged with API-retrieved data and eventually spit out to a [Shiny](http://shiny.rstudio.com/gallery/)/R report server (see the two screenshots).  The dashboard has hyperlinks that take them to the specific client/event/calendar record in REDCap.

@jtwinn, what group are you with?  If this approach may interest you, I'm happy to chat sometime.

```sql
SELECT 
      redcapv3.redcap_events_calendar.event_date,
      redcapv3.redcap_events_calendar.event_time,
      redcapv3.redcap_events_calendar.cal_id,
      redcapv3.redcap_events_calendar.record,
      redcapv3.redcap_events_calendar.event_id,
      redcapv3.redcap_events_calendar.baseline_date,
      redcapv3.redcap_events_calendar.group_id,
      redcapv3.redcap_data_access_groups.group_name,
      redcapv3.redcap_events_calendar.event_status,
      redcapv3.redcap_events_metadata.descrip as event_description,
      redcapv3.redcap_events_metadata.arm_id,
      redcapv3.redcap_events_arms.arm_num,
      redcapv3.redcap_events_arms.arm_name,
      redcapv3.redcap_events_metadata.day_offset,
      redcapv3.redcap_events_calendar.project_id
  FROM
      redcapv3.redcap_events_calendar
          LEFT JOIN
      redcapv3.redcap_data_access_groups ON (redcapv3.redcap_events_calendar.project_id = redcapv3.redcap_data_access_groups.project_id
          AND redcapv3.redcap_events_calendar.group_id = redcapv3.redcap_data_access_groups.group_id)
          LEFT JOIN
      redcapv3.redcap_events_metadata ON (redcapv3.redcap_events_calendar.event_id = redcapv3.redcap_events_metadata.event_id)
          LEFT JOIN
      redcapv3.redcap_events_arms ON (redcapv3.redcap_events_metadata.arm_id = redcapv3.redcap_events_arms.arm_id)
  WHERE
      redcapv3.redcap_events_calendar.project_id = 35
      --    AND DATE(redcapv3.redcap_events_calendar.event_date) BETWEEN DATE(CURRENT_DATE() - INTERVAL 60 DAY) AND DATE(CURRENT_DATE() + INTERVAL 45 DAY)
  ORDER BY redcapv3.redcap_events_calendar.event_date
```

![image](https://cloud.githubusercontent.com/assets/1372890/9773697/66c36b00-5709-11e5-8bdc-3682905c039d.png)

![image](https://cloud.githubusercontent.com/assets/1372890/9773689/5add6eee-5709-11e5-9be4-e22b2f6e591f.png)

**Comment by nutterb** [comment]
@jtwinn I'm curious about your purposes behind matching records to data-entry-person.  This seems like a messy match, given that there could be multiple data entry people for a given subject.  I can't think of what could be learned from such a match.  (That isn't a criticism of your intent; more a statement of my lack of creativity).

**Comment by jtwinn** [comment]
Looking to match last entry to record. We are tracking patient encounters and I need to know last contact for each patient.

**Comment by jtwinn** [comment]
@wibeasley  I am at Yale and we are using REDCap as maintained by the Program on Aging.  Thanks for entertaining my question.  I am slowly learning that end-users are a part of a guarded group controlled by site admins.  You have the type of set up that I am looking for!  However, I do not think I will be granted access to an ODBC connection for "Security" Reasons.  

@nutterb I understand your thought process.  For this situation while not foolproof, it could work.  I may just resolve to asking the network navigators to enter their user id every time they initiate a record.

Please note that our site admin promised to put in a request to add those modules to the API.  So, if you want/need that data in the API please contact Vanderbilt too so they can see that there is interest.  

Thanks all.  I've learned so much.

**Comment by nutterb** [comment]
@jtwinn I think you're right that the activity log (or whatever it's official name is) could serve as a proxy for last contact.  Each entry in the log shows what record was changed, what fields were changed for that record, and which user made the changes.  if you know what fields indicate that the data entry person had contact with the patient, you can parse the log to identify if any of those fields were changed, and grab the date the change was made (as well as the user id, if needed).  Then that can all be merged back to the record id exported from the API.  We, unfortunately, just can't give you the log through the API.

**Comment by haozhu233** [comment]
Regarding the log exportation, I do notice that for each redcap project has a unique download link with a unique id. For example, in my institution, it is https://xxxxxxxxxxxxxxxxx/redcap/redcap_v6.6.2/Logging/csv_export.php?pid=100.

I tried to use curl or some script in powershell to download this file with my username and password. I got a file but it says it detected that the javascript in my browser was disabled so it could not fetch the logging data into a file. I'm thinking maybe by using some ruby/python packages, such as [`mechanize`](http://wwwsearch.sourceforge.net/mechanize/), you can write a script to create a fake browser to fetch the log file automatically. @jtwinn Do you want to give it a try?

**Comment by jtwinn** [comment]
Sure. Will give it a go.  I got the same error msg with RCurl.

**Comment by haozhu233** [comment]
@wibeasley I run into the calendar issue recently. I just wish this could be a stackoverflow post so I can upvote your solution. Thank you! :)

**Comment by wibeasley** [comment]
I'm glad it helped.  If you want to see more, the data munging is in a private repo, but the Shiny [app](http://shiny.ouhsc.edu/MReportingPublic/Shiny/UpcomingSchedule/) and [code](https://github.com/OuhscBbmc/MReportingPublic/tree/master/Shiny/UpcomingSchedule) is public.  I'm happy to chat with you too if it might help.
